import type { ChapterManifest, ChapterStep, VisualControl, VisualTeaching } from "./schema.ts";

type RawChapterStep = Omit<ChapterStep, "learnerQuestion" | "placement">;
type RawChapterManifest = Omit<ChapterManifest, "steps"> & {
  steps: readonly RawChapterStep[];
};

/** One concise question is shown beside every scene, never a paragraph of instructions. */
const learnerQuestions: Record<string, string> = {
  "market-early-share": "How established is rare-earth-free traction today?",
  "car-transparent-cutaway": "Where does the traction motor sit in an EV?",
  "power-path-flow": "How does battery electricity reach the wheels?",
  "drive-unit-extract": "What else sits beside the motor in the drive unit?",
  "motor-isolation": "What are the two moving and stationary parts inside the motor?",
  "pmsm-assemble-stator": "What makes up the stationary stator ring?",
  "pmsm-three-phase-field": "How can three currents make one field rotate?",
  "pmsm-rotor-lock": "Why does the rotor stay in step with the moving field?",
  "ipm-rotor-cutaway": "Why are permanent magnets buried inside the rotor?",
  "ipm-reluctance-overlay": "Is the magnet doing all the turning?",
  "remanence-strength": "What stays after the helper goes?",
  "coercivity-lock": "What can turn a magnet backwards?",
  "heat-demagnetisation": "What can leave a magnet weaker?",
  "dy-tb-tradeoff": "What do Dy and Tb change?",
  "grain-boundary-diffusion": "Where can protection help?",
  "cooling-and-smco": "What does cooling change?",
  "light-and-heavy-ree-supply": "Which rare-earth exposure is this dated control notice actually about?",
  "mitigation-ladder": "What is the smallest credible change an OEM can make first?",
  "back-emf-speed-sweep": "Why does a permanent magnet limit high-speed voltage headroom?",
  "field-weakening-current": "Why does a PMSM spend current to cancel its own flux?",
  "inverter-fault-at-speed": "What remains active when a permanent-magnet inverter is gated off?",
  "sync-async-family-tree": "Which motors keep pace with the field, and which need slip?",
  "induction-cage-lab": "How does a squirrel cage create its own rotor field?",
  "induction-slip-heat-coast": "How do load, slip, heat and coasting connect?",
  "induction-mixed-axle": "Why might an OEM use induction on only one axle?",
  "wound-field-lab": "What changes when magnets become a powered rotor winding?",
  "brushed-contactless-status": "Which EESM evidence is production, and which is contactless development?",
  "pure-synrm-lab": "How can shaped steel make torque with no rotor magnet or winding?",
  "pm-assisted-synrm-lab": "Why add small magnets back into a reluctance rotor?",
  "srm-aem-lab": "Why must SRM peak power be read with its continuous duty?",
  "ferrite-material-not-architecture": "What changes when only the permanent-magnet chemistry changes?",
  "axial-flux-geometry": "Why is axial flux a geometry, not a magnet chemistry?",
  "proterial-power-speed": "What makes two motor power figures comparable?",
  "iron-nitride-property-board": "Why is saturation alone not enough to judge a permanent magnet?",
  "matter-variable-flux": "When can deliberately adjustable flux be useful?",
  "stackable-motor-builder": "Which motor choices can stack instead of compete?",
  "vehicle-survivors-and-changes": "Which vehicle systems change when the drive architecture changes?",
  "inverter-and-cooling-burden": "Where does each alternative move the engineering burden?",
  "swap-burden-spectrum": "Why are some changes smaller than a full drive-unit redesign?",
  "validation-runway": "What validation work follows an architecture change?",
  "mixed-axle-revisit": "Can two axle motors solve different jobs in one vehicle?",
  "two-markets-switch": "Why are EV traction and industrial-motor comparisons different?",
  "evidence-maturity-lanes": "What does a maturity label actually prove?",
  "claim-condition-checker": "What information must travel with a technical claim?",
  "india-capability-stack": "What capabilities can India build alongside motor choices?",
  "final-decision-map": "Which problem are you actually trying to solve first?",
};

/** The default route is short enough for a curious beginner to finish. */
const mainStepIds = new Set([
  "car-transparent-cutaway",
  "power-path-flow",
  "drive-unit-extract",
  "motor-isolation",
  "pmsm-assemble-stator",
  "pmsm-three-phase-field",
  "pmsm-rotor-lock",
  "ipm-rotor-cutaway",
  "ipm-reluctance-overlay",
  "remanence-strength",
  "coercivity-lock",
  "heat-demagnetisation",
  "dy-tb-tradeoff",
  "light-and-heavy-ree-supply",
  "mitigation-ladder",
  "back-emf-speed-sweep",
  "field-weakening-current",
  "sync-async-family-tree",
  "induction-cage-lab",
  "induction-slip-heat-coast",
  "wound-field-lab",
  "pure-synrm-lab",
  "ferrite-material-not-architecture",
  "axial-flux-geometry",
  "iron-nitride-property-board",
  "stackable-motor-builder",
  "vehicle-survivors-and-changes",
  "swap-burden-spectrum",
  "two-markets-switch",
  "india-capability-stack",
  "final-decision-map",
]);

const next = (consequence: string): VisualControl => ({
  id: "next",
  label: "Next",
  kind: "next",
  consequence,
});

const back = (consequence: string): VisualControl => ({
  id: "back",
  label: "Back",
  kind: "back",
  consequence,
});

const play = (consequence: string): VisualControl => ({
  id: "play",
  label: "Play / pause",
  kind: "play",
  consequence,
});

const visual = (
  device: VisualTeaching["device"],
  visibleConsequence: string,
  interaction: string,
  fallback: string,
): VisualTeaching => ({ device, visibleConsequence, interaction, fallback });

const rawChapters = [
  {
    id: "where-the-motor-lives",
    number: 1,
    title: "Where the motor lives",
    premise: "Start with the car, not the motor diagram.",
    steps: [
      {
        id: "market-early-share",
        title: "The transition has barely started",
        learningGoal: "Understand why alternatives should be shown as an emerging landscape, not as a market that has already replaced PMSM.",
        visual: visual(
          "before-after-comparison",
          "An illustrative adoption band moves from today's uneven disclosure to a hypothetical future mix, without asserting a precise market share.",
          "Drag the adoption handle; the starting state is labelled 'emerging, unevenly disclosed' rather than given an unsupported percentage.",
          "A labelled qualitative adoption band with an explicit evidence-warning chip.",
        ),
        controls: [
          { id: "market-share", label: "Illustrative adoption", kind: "slider", consequence: "Moves a clearly hypothetical adoption band while keeping today's evidence state visible." },
          next("Moves into the car that contains one of those motors."),
        ],
        claimIds: ["market-rare-earth-free-share-small", "india-opportunity-capabilities"],
        copy: {
          glance: "Most EV traction motors still use permanent magnets. The alternative market is early, not settled.",
          why: "That makes this a design race as much as a supply-chain story: an immature market is where new manufacturing capability can still matter.",
          evidence: "No qualifying source in the launch audit supports a precise rare-earth-free share. The on-stage adoption band is qualitative only.",
        },
        reducedMotionState: "Static qualitative adoption band with an evidence-warning badge.",
      },
      {
        id: "car-transparent-cutaway",
        title: "Find the traction motor",
        learningGoal: "Locate the battery, inverter, traction motor and axle within a representative EV.",
        visual: visual(
          "transparent-cutaway",
          "The car body fades to reveal only a battery pack, one drive unit and the wheels it turns.",
          "Tap battery, drive unit or wheel; an optional layout toggle appears only after the basic spatial relationship is clear.",
          "A clean three-object car cutaway: battery, drive unit and wheels.",
        ),
        controls: [
          { id: "car-hotspots", label: "Inspect component", kind: "hotspot", consequence: "Dims the rest of the car and reveals the selected object's role." },
          { id: "axle-layout", label: "Explore layouts", kind: "toggle", consequence: "Optionally adds a second axle drive without changing the simple default picture." },
          next("Traces energy from the battery to the road."),
        ],
        claimIds: [],
        copy: {
          glance: "The battery stores energy. A drive unit near an axle turns the wheels.",
          why: "Start with three things only: battery, drive unit and wheels. The next scene opens the path between them.",
          evidence: "This is a brand-neutral spatial teaching model. It does not claim one universal EV package.",
        },
        reducedMotionState: "Static transparent car with only battery, drive unit and wheels labelled.",
      },
      {
        id: "power-path-flow",
        title: "Electricity becomes wheel torque",
        learningGoal: "Distinguish electrical power before the motor from mechanical rotation after it.",
        visual: visual(
          "animated-flow",
          "A visible path changes from DC at the battery to three coloured phase currents, then to rotating shaft and wheels.",
          "Press play or scrub the energy pulse through battery, inverter, motor, reduction gear, differential and wheels.",
          "A single-frame route diagram with distinct electrical and mechanical arrows.",
        ),
        controls: [play("Animates the causal route one stage at a time."), next("Zooms to the axle drive unit.")],
        claimIds: [],
        copy: {
          glance: "Battery DC → inverter → motor → reduction gear → axle → wheels.",
          why: "The inverter is not a side detail. It decides the current timing that makes the motor's field move.",
          evidence: "The route is an explanatory block diagram; real e-axles package the same functions differently.",
        },
        reducedMotionState: "Segmented static arrows change from electrical notation to shaft and wheel rotation notation.",
      },
      {
        id: "drive-unit-extract",
        title: "Pull the drive unit out",
        learningGoal: "See the motor in relation to the inverter, reduction gear and cooling system before opening it.",
        visual: visual(
          "exploded-model",
          "The complete axle drive unit detaches from the car while the wheel connection remains ghosted behind it, then opens into inverter, motor and reduction gears.",
          "Tap one clear control to open the drive unit beside its ghosted axle connection.",
          "A still extracted-and-opened drive unit beside the ghosted wheel connection, with three component leader lines.",
        ),
        controls: [
          { id: "open-drive-unit", label: "Open drive unit", kind: "toggle", consequence: "Moves the same drive unit from its axle location into a readable, opened inspection position." },
          next("Separates the drive unit into its working parts."),
        ],
        claimIds: [],
        copy: {
          glance: "A traction motor is one member of a tightly coupled drive unit.",
          why: "Alternative motors may leave much of the car alone while forcing changes inside this unit: inverter, cooling, package and control logic.",
          evidence: "The specific integration consequences are developed in Chapter 7.",
        },
        reducedMotionState: "Drive unit pictured beside a ghosted axle, with four separated labelled modules.",
      },
      {
        id: "motor-isolation",
        title: "Now isolate the machine",
        learningGoal: "Arrive at a motor scale that makes the stator and rotor understandable.",
        visual: visual(
          "exploded-model",
          "Inverter, reducer and coolant fade back while the motor remains centred and grows to fill the technical stage.",
          "Tap 'open motor' to split the casing by a small, controlled distance.",
          "A clean motor cross-section with its outer casing partly transparent.",
        ),
        controls: [{ id: "open-motor", label: "Open motor", kind: "toggle", consequence: "Reveals the stationary outer stator and spinning inner rotor." }, next("Builds the PMSM from the outside in.")],
        claimIds: [],
        copy: {
          glance: "Inside the housing are two essential parts: a stationary stator and a spinning rotor.",
          why: "Everything that follows is about how those two parts create and chase a rotating magnetic field.",
          evidence: "The next chapter uses a representative interior-permanent-magnet motor, not a proprietary OEM drawing.",
        },
        reducedMotionState: "Transparent-housing motor with stator and rotor labelled in place.",
      },
    ],
  },
  {
    id: "how-a-pmsm-turns",
    number: 2,
    title: "How a PMSM turns",
    premise: "First make a field move. Then give it a rotor to pull.",
    steps: [
      {
        id: "pmsm-assemble-stator",
        title: "Build the stationary ring",
        learningGoal: "Identify the stator laminations, three copper winding groups, air gap and rotor space.",
        visual: visual(
          "exploded-model",
          "One motor cross-section keeps the stationary stator ring, air gap and quiet rotor visible for comparison.",
          "Choose Stator, Rotor or Both to isolate the part you want to inspect.",
          "A still motor cross-section with a three-way part-isolate control and simple leader labels.",
        ),
        controls: [
          { id: "stator-isolate", label: "Stator / Rotor / Both", kind: "select", consequence: "Fades the other parts so the selected stator, rotor or both are easier to compare." },
          next("Feeds timed current into the three coil groups."),
        ],
        claimIds: ["pmsm-stator-three-phase-field"],
        copy: {
          glance: "The stator is a steel ring wound with three copper coil groups.",
          why: "No rotor has moved yet. The first trick is to make the magnetic north pole appear to move around this ring.",
          evidence: "The winding layout is a simplified three-phase teaching cross-section, not a manufacturing drawing.",
        },
        reducedMotionState: "A still motor cross-section with the stator selected; choose Stator, Rotor or Both to compare the parts.",
      },
      {
        id: "pmsm-three-phase-field",
        title: "Make a field rotate",
        learningGoal: "Connect three offset current waves to a single rotating stator-field vector.",
        visual: visual(
          "animated-field",
          "Three current waveforms stay 120 electrical degrees apart while a north-field vector sweeps around the empty stator bore.",
          "Play, pause or scrub the waveforms; change electrical frequency to change the vector's speed.",
          "Three frozen waveform positions linked by colour to three coils and one field-vector arrow.",
        ),
        controls: [
          { id: "field-play", label: "Play field", kind: "play", consequence: "Advances all three phases and rotates the resultant field vector." },
          { id: "frequency", label: "Electrical frequency", kind: "slider", consequence: "Changes field-vector rotation speed while the coil geometry stays still." },
          next("Places a permanent-magnet rotor inside the field."),
        ],
        claimIds: ["pmsm-stator-three-phase-field"],
        copy: {
          glance: "Three timed currents make one magnetic field appear to travel around the stator.",
          why: "Nothing physical is orbiting. The current pattern changes, so the strongest electromagnetic direction moves around the ring.",
          evidence: "The simulation is intentionally idealised. Its purpose is to make phase timing visible.",
        },
        reducedMotionState: "Three phase snapshots with a sequential arrow showing the field's next position.",
      },
      {
        id: "pmsm-rotor-lock",
        title: "Give the field something to pull",
        learningGoal: "Understand synchronous speed and the torque angle under load.",
        visual: visual(
          "force-vector-overlay",
          "A permanent-magnet rotor enters the rotating field; under load its north pole trails the stator field by a visible torque angle but keeps matching its speed.",
          "Increase shaft load and watch the torque angle grow; play and pause the paired field/rotor motion.",
          "A still overlay of stator-field vector, rotor-field vector, shaft load and torque angle.",
        ),
        controls: [
          { id: "shaft-load", label: "Shaft load", kind: "slider", consequence: "Increases the torque angle without creating an induction-style speed gap." },
          play("Runs field and rotor together at matched synchronous speed."),
          next("Cuts the rotor open to show why its magnets sit inside steel."),
        ],
        claimIds: ["pmsm-synchronous-torque-angle"],
        copy: {
          glance: "The stator field stays a little ahead. The rotor follows at the same speed.",
          why: "More load means a larger angular lag, not slip. That fixed relationship is why this is called synchronous.",
          evidence: "The torque-angle relationship is a teaching model. It does not show the controller's full current-vector calculation.",
        },
        reducedMotionState: "Static field and rotor vectors at a visible torque angle, with a load arrow.",
      },
      {
        id: "ipm-rotor-cutaway",
        title: "Why bury the magnets?",
        learningGoal: "See both mechanical retention and magnetically unequal paths inside an IPM rotor.",
        visual: visual(
          "microscopic-cutaway",
          "The rotor opens to reveal buried magnets, steel bridges and flux routes; a speed toggle adds an outward centrifugal-force overlay.",
          "Toggle 'high speed' and 'show flux paths' to compare mechanical and magnetic reasons for interior placement.",
          "A rotor cross-section with static flux arrows and restrained outward force arrows.",
        ),
        controls: [
          { id: "rotor-speed", label: "High speed", kind: "toggle", consequence: "Adds the retention problem magnets would face if simply mounted on the rotor surface." },
          { id: "flux-paths", label: "Show flux paths", kind: "toggle", consequence: "Reveals easier steel paths and magnetically harder magnet paths." },
          next("Separates magnet torque from reluctance torque."),
        ],
        claimIds: ["ipm-magnets-buried"],
        copy: {
          glance: "Buried magnets are held by steel and reshape the rotor's magnetic paths.",
          why: "Steel carries magnetic flux easily. A route through magnet material is harder. That deliberate lopsidedness has a second torque effect.",
          evidence: "Rotor geometries vary. This cross-section is a generic IPM mechanism view.",
        },
        reducedMotionState: "Single IPM rotor cross-section with annotated retention bridges and flux paths.",
      },
      {
        id: "ipm-reluctance-overlay",
        title: "One rotor, two pulls",
        learningGoal: "See that the magnet and shaped steel both help turn one rotor.",
        visual: visual(
          "before-after-comparison",
          "One rotor keeps its magnets and shaped steel while two quiet arrows meet at the same shaft.",
          "Choose magnet pull, steel alignment or both to see what helps turn the shaft.",
          "One rotor with a field arrow, magnet direction, steel direction and qualitative shaft arrows.",
        ),
        controls: [
          { id: "torque-blend", label: "Magnet pull / steel alignment", kind: "slider", consequence: "Shows one contribution or both without changing the stator field." },
          next("Shows one shaft with two pulls.")],
        claimIds: ["ipm-reluctance-torque", "pm-assisted-synrm-stack"],
        copy: {
          glance: "The magnet pulls, and the shaped steel also tries to line up. Both turn the same shaft.",
          why: "This second pull is called reluctance torque. The rotor wants both its permanent poles and its easy steel path to line up with the moving stator field.",
          evidence: "An IPM-SynRM combines those effects in one rotor. This corrects an exclusive-box taxonomy.",
        },
        reducedMotionState: "One still rotor with a magnet pull, a steel-alignment pull and one shared shaft.",
      },
    ],
  },
  {
    id: "why-the-magnet-needs-nd-dy-tb",
    number: 3,
    title: "Why the magnet needs Nd, Dy and Tb",
    premise: "A traction magnet needs both strength and resistance to reversal.",
    steps: [
      {
        id: "remanence-strength",
        title: "First: retained field",
        learningGoal: "Understand remanence as the field a magnet retains on its own.",
        visual: visual(
          "force-vector-overlay",
          "A helper field disappears around one simple magnet while its retained field remains; a small weaker-versus-stronger comparison stays beside it.",
          "Remove the helper field, then compare weaker and stronger retained field.",
          "One still magnet with its helper removed, retained field visible, and two small qualitative comparison magnets.",
        ),
        controls: [
          { id: "remove-helper-field", label: "Remove helper field", kind: "toggle", consequence: "Removes the helper field while the magnet's retained field stays visible." },
          { id: "retained-field-comparison", label: "Weaker / stronger retained field", kind: "select", consequence: "Changes a simple qualitative retained-field comparison without making a data chart." },
          next("Tests whether that field stays pointed the right way."),
        ],
        claimIds: ["magnet-remanence-definition", "ndfeb-division-of-labour"],
        copy: {
          glance: "A magnet can hold some field after help is removed.",
          why: "Iron supplies much of the strength. Rare-earth chemistry helps resist reversal.",
          evidence: "Conceptual field view only. No material grade, field value or data chart is shown.",
        },
        reducedMotionState: "Helper removed, retained field clear, with a complete weaker-versus-stronger comparison.",
      },
      {
        id: "coercivity-lock",
        title: "Second: resist reversal",
        learningGoal: "Understand coercivity as resistance to a reversing field.",
        visual: visual(
          "before-after-comparison",
          "One opposing-field control acts on two illustrative magnets with different coercivity; the lower-coercivity example reverses first.",
          "Move the opposing-field range and compare the two magnets under the same input.",
          "Two still magnets with the lower-coercivity example reversed first and the higher-coercivity example still aligned.",
        ),
        controls: [{ id: "opposing-field", label: "Opposing field", kind: "slider", consequence: "Pushes against both illustrative magnets; the lower-coercivity example reverses first." }, next("Adds heat to the same reversal test.")],
        claimIds: ["magnet-coercivity-definition", "ndfeb-division-of-labour"],
        copy: {
          glance: "An opposing field can try to turn a magnet backwards.",
          why: "These two magnets are only an illustration. The lower-coercivity magnet turns first.",
          evidence: "Qualitative reversal comparison only. No universal threshold shown.",
        },
        reducedMotionState: "Two illustrative magnets under one opposing field, with the lower-coercivity example flipped first.",
      },
      {
        id: "heat-demagnetisation",
        title: "Heat makes reversal easier",
        learningGoal: "Connect relative heat, an opposing field and a latched demagnetised patch.",
        visual: visual(
          "thermal-map",
          "Independent relative-heat and opposing-field controls act on one magnet. A high combination can latch a reversed patch and weaken the retained field; cooling removes the heat aura but not that patch.",
          "Raise relative heat and opposing field independently, then lower heat after a patch forms.",
          "A cooled magnet with a visible patch that remains and a weakened retained field.",
        ),
        controls: [
          { id: "relative-heat", label: "Relative heat", kind: "slider", consequence: "Shows or removes a qualitative heat aura without claiming a universal temperature." },
          { id: "opposing-field", label: "Opposing field", kind: "slider", consequence: "Pushes the same magnet against its illustrated reversal margin." },
          { id: "fresh-magnet", label: "Fresh magnet", kind: "toggle", consequence: "Clears the illustrative latched patch by replacing the sample rather than repairing it." },
          next("Explains why a little Dy or Tb is valuable."),
        ],
        claimIds: ["traction-temperature-range", "coercivity-temperature-sensitivity"],
        copy: {
          glance: "Heat plus an opposing field can leave a magnet weaker, even after it cools.",
          why: "Heat and an opposing field can leave a patch turned backwards. Cooling removes the heat aura, but a patch can remain. Choose Fresh magnet to start again.",
          evidence: "Relative heat and reversal margin only; no universal threshold shown.",
        },
        reducedMotionState: "A cooled end state with the heat aura gone, the patch still present and the retained field weakened.",
      },
      {
        id: "dy-tb-tradeoff",
        title: "Dy/Tb adds hot margin",
        learningGoal: "See why heavy rare earths protect coercivity but cannot simply be added without limit.",
        visual: visual(
          "parameter-slider",
          "A clearly named fresh comparison sample uses a three-stop Dy/Tb protection control. Increasing protection expands reversal margin while reducing the retained-field indicator at the same time.",
          "Move the three-stop Dy/Tb protection range and compare reversal margin with retained field.",
          "A fresh still magnet with a wider illustrated reversal margin and a shorter retained field at the highest protection stop.",
        ),
        controls: [
          { id: "dy-tb-protection", label: "Dy/Tb protection", kind: "slider", consequence: "Raises reversal margin while reducing the retained field/strength indicator in the same action." },
          { id: "open-grain-boundary-diffusion", label: "Explore grain edge", kind: "hotspot", consequence: "Opens the optional grain-boundary diffusion lab without changing the four-step progress." },
          { id: "open-cooling-and-smco", label: "Compare cooling", kind: "hotspot", consequence: "Opens the optional cooling and SmCo lab without changing the four-step progress." },
          next("Moves the protection to where it is most useful."),
        ],
        claimIds: ["dy-tb-thermal-role", "dy-strength-tradeoff", "illustrative-magnet-composition"],
        copy: {
          glance: "Dy and Tb help a hot magnet resist reversal. They do not cool it.",
          why: "Fresh comparison sample: this does not repair the heated magnet. More protection gives more reversal margin and less retained field/strength.",
          evidence: "Qualitative retained-field and reversal-margin trade-off only. No universal alloy recipe is shown.",
        },
        reducedMotionState: "Fresh comparison sample at the highest protection stop with more reversal margin and less retained field.",
      },
      {
        id: "grain-boundary-diffusion",
        title: "Protect the grain's edge",
        learningGoal: "Understand why grain-boundary diffusion targets a shell rather than mixing dysprosium uniformly through the magnet.",
        visual: visual(
          "microscopic-cutaway",
          "Uniform mixing and an edge-shell treatment are shown side by side. An illustrative seed test begins near a grain edge where reversal can begin.",
          "Toggle uniform versus grain-boundary protection, then run the illustrative seed test.",
          "Side-by-side static uniform-mix and edge-shell grain views with their complete seed-test result.",
        ),
        controls: [
          { id: "protection-placement", label: "Uniform / grain boundary", kind: "toggle", consequence: "Highlights uniform mixing or protection focused near a grain edge." },
          { id: "run-seed-test", label: "Run seed test", kind: "toggle", consequence: "Shows an illustrative seed path without claiming a guaranteed stop." },
          back("Returns to the fresh Dy/Tb comparison sample.")],
        claimIds: ["gbd-grain-shell"],
        copy: {
          glance: "Protection can be focused near a grain edge where reversal can begin.",
          why: "Protection can be focused near an edge where reversal can begin. This is an illustrative process, not a promise for every magnet.",
          evidence: "Illustrative mechanism view. It does not imply every commercial magnet uses this process or that a seed is guaranteed to stop.",
        },
        reducedMotionState: "Side-by-side uniform-mix and edge-shell grains with a complete static seed-test result.",
      },
      {
        id: "cooling-and-smco",
        title: "Lower heat, lower the burden",
        learningGoal: "Compare a cooling intervention with a higher-temperature permanent-magnet alternative.",
        visual: visual(
          "thermal-map",
          "A hot rotor and a cooled rotor sit side by side. A reader can separately open a qualified SmCo position card.",
          "Toggle rotor oil cooling and, separately, Compare SmCo.",
          "Static hot-versus-cooled rotor comparison with cooling flow shown and a separate SmCo position card.",
        ),
        controls: [
          { id: "rotor-oil-cooling", label: "Rotor oil cooling", kind: "toggle", consequence: "Shows or hides thermal management around the cooled rotor without inferring material substitution." },
          { id: "compare-smco", label: "Compare SmCo", kind: "toggle", consequence: "Shows or hides a separate qualified permanent-magnet position card, not a universal comparison." },
          back("Returns to the fresh Dy/Tb comparison sample.")],
        claimIds: ["rotor-oil-cooling-reduces-hree", "smco-temperature-position"],
        copy: {
          glance: "Cooling is thermal management. It does not prove Dy/Tb removal.",
          why: "Cooling manages heat. It does not show that Dy or Tb can be removed. Compare SmCo only as a qualified position, not a universal answer.",
          evidence: "Cooling evidence is thermal-management evidence only. No rotor temperature limit or Dy/Tb-reduction claim is shown.",
        },
        reducedMotionState: "Hot and cooled rotors side by side with a separate qualified SmCo position card.",
      },
    ],
  },
  {
    id: "reduce-exposure-or-replace-pmsm",
    number: 4,
    title: "Reduce exposure—or replace the PMSM",
    premise: "The choice is not only 'rare earths' versus 'no rare earths'.",
    steps: [
      {
        id: "light-and-heavy-ree-supply",
        title: "Split the supply problem",
        learningGoal: "Distinguish Nd/Pr from Dy/Tb and avoid treating all rare-earth exposure as one interchangeable risk.",
        visual: visual(
          "matrix",
          "A material-supply matrix separates light rare earths from heavy rare earths and maps them onto magnet roles, current control context and reduction levers.",
          "Click Nd/Pr or Dy/Tb to trace each material from magnet role to the relevant mitigation route.",
          "A two-column material map with arrows into strength, coercivity and mitigation routes.",
        ),
        controls: [{ id: "ree-select", label: "Select material group", kind: "select", consequence: "Highlights only the associated magnet function and supply response." }, next("Builds the least-disruptive response ladder.")],
        claimIds: ["hree-controls-distinct-from-ndpr", "dy-tb-thermal-role"],
        copy: {
          glance: "Nd/Pr gives the permanent magnet its main field. Dy/Tb helps that field survive heat.",
          why: "If the immediate pressure is heavy rare earths, reducing the Dy/Tb burden can be faster than discarding the whole motor architecture.",
          evidence: "Export-control coverage is date-sensitive and remains a verification-required evidence item.",
        },
        reducedMotionState: "Two-column material-role matrix with static mitigation arrows.",
      },
      {
        id: "mitigation-ladder",
        title: "Start with the smallest change",
        learningGoal: "Place cooling, grain-boundary diffusion, reduced-HREE magnets and full architecture changes on a clear intervention ladder.",
        visual: visual(
          "timeline",
          "A change ladder expands from rotor cooling to grain-boundary diffusion, reduced-HREE NdFeB, alternate magnet chemistry and new motor architecture; the vehicle systems affected grow at each rung.",
          "Select a rung to reveal what remains unchanged and what must be redesigned.",
          "A static five-rung ladder with unchanged components in neutral grey and changed components in accent colour.",
        ),
        controls: [{ id: "ladder-rung", label: "Choose intervention", kind: "select", consequence: "Highlights the corresponding retained and changed hardware." }, next("Shows a PMSM limit that materials alone do not remove.")],
        claimIds: ["reduced-hree-near-drop-in", "proterial-hree-free-ndfeb", "vehicle-swap-burden"],
        copy: {
          glance: "Not every supply response means a new car. HREE-free NdFeB, cooling and grain-boundary diffusion leave more in place than a new motor architecture.",
          why: "The ladder matters because it separates short-term resilience options from longer-term propulsion redesign.",
          evidence: "'Near-drop-in' is explicitly qualified: it still needs motor-specific validation.",
        },
        reducedMotionState: "Five-rung intervention ladder with a static change footprint at each rung.",
      },
      {
        id: "back-emf-speed-sweep",
        title: "The magnet keeps generating",
        learningGoal: "Understand why a permanent rotor creates a high-speed voltage constraint.",
        visual: visual(
          "parameter-slider",
          "Increasing shaft speed raises a back-EMF trace toward a fixed DC-bus ceiling; the motor's permanent field stays visibly on throughout.",
          "Move the speed slider until back-EMF approaches the DC-bus line.",
          "A frozen voltage-versus-speed curve with the DC-bus ceiling and a permanent rotor field shown beside it.",
        ),
        controls: [{ id: "speed-sweep", label: "Motor speed", kind: "slider", consequence: "Raises the back-EMF trace toward the available battery voltage." }, next("Adds the current used to keep going faster.")],
        claimIds: ["back-emf-constraint"],
        copy: {
          glance: "At high speed, the permanent rotor acts like a generator pushing voltage back into the stator.",
          why: "Eventually that back-EMF approaches the DC bus. The inverter cannot simply keep forcing more current in the same way.",
          evidence: "This is an idealised speed sweep intended to explain the causal limit, not a vehicle-specific calibration chart.",
        },
        reducedMotionState: "Back-EMF curve meeting a DC-bus ceiling at a labelled high-speed region.",
      },
      {
        id: "field-weakening-current",
        title: "Pay current to cancel flux",
        learningGoal: "See the purpose and cost of field weakening.",
        visual: visual(
          "force-vector-overlay",
          "A field-weakening current vector appears opposite part of the magnet flux. The net field shrinks while the torque-producing current does not grow with it.",
          "Drag the high-speed slider past the voltage ceiling to introduce field-weakening current.",
          "A current-vector diagram with magnet flux, weakening current and torque component clearly separated.",
        ),
        controls: [{ id: "field-weakening", label: "Go beyond base speed", kind: "slider", consequence: "Adds a cancelling current component and visibly reduces net flux." }, next("Tests what happens if the inverter stops commanding anything.")],
        claimIds: ["field-weakening-no-torque"],
        copy: {
          glance: "Field weakening spends current to push back against the field you permanently installed.",
          why: "The torque-producing component and the cancelling component are not the same job. A controllable rotor field offers a different high-speed trade-off.",
          evidence: "The vector view intentionally isolates field-weakening's role from full control-algorithm detail.",
        },
        reducedMotionState: "Static current-vector triangle with a labelled cancelling component.",
      },
      {
        id: "inverter-fault-at-speed",
        title: "A field you cannot turn off",
        learningGoal: "Compare permanent-field and controllable-field behaviour during an inverter fault at speed.",
        visual: visual(
          "before-after-comparison",
          "At the same wheel speed, a PMSM keeps a rotor field and generator arrow after inverter failure, while a wound-field example fades its commanded field when excitation is removed.",
          "Press 'inverter fault' and compare the two machines; then reset.",
          "Two static fault-state diagrams with an active-field warning and a controllable-excitation comparison.",
        ),
        controls: [{ id: "fault-test", label: "Inverter fault", kind: "toggle", consequence: "Stops commanded drive current while showing whether the rotor field persists." }, next("Sorts all the motor families by their rotor-field behaviour.")],
        claimIds: ["pmsm-inverter-failure-risk", "wound-field-advantages-costs"],
        copy: {
          glance: "A permanent magnet cannot be commanded off. An excited rotor can.",
          why: "That difference changes fault handling and high-speed control even before supply-chain questions enter the picture.",
          evidence: "Fault behaviour is a safety-critical engineering topic; this teaching comparison is flagged for detailed source validation.",
        },
        reducedMotionState: "Side-by-side PMSM and wound-field fault-state diagrams.",
      },
      {
        id: "sync-async-family-tree",
        title: "Two families, not six boxes",
        learningGoal: "Place PMSM, wound field, reluctance and induction on a synchronous/asynchronous family map.",
        visual: visual(
          "matrix",
          "A family tree groups permanent-magnet, wound-field, SynRM and SRM routes under synchronous behaviour, while induction sits under asynchronous behaviour with its slip arrow.",
          "Select a motor tile to animate only its rotor-field source and speed relationship.",
          "A static family tree with field-source icons and a single slip marker on induction.",
        ),
        controls: [{ id: "family-select", label: "Inspect family", kind: "select", consequence: "Highlights the rotor-field source and whether the rotor matches field speed." }, next("Opens the alternative motor laboratory.")],
        claimIds: ["motor-family-sync-async", "stackable-technologies"],
        copy: {
          glance: "Synchronous means the rotor field keeps pace. Induction needs slip to make its rotor field at all.",
          why: "The branches are useful, but they do not make every technology an exclusive competitor. Some choices stack inside the same motor.",
          evidence: "The family tree is a teaching taxonomy used consistently throughout the experience.",
        },
        reducedMotionState: "Static two-branch family tree with field-source icons.",
      },
    ],
  },
  {
    id: "alternative-motor-laboratory",
    number: 5,
    title: "Alternative motor laboratory",
    premise: "Change the rotor. Keep the causal mechanism visible.",
    steps: [
      {
        id: "induction-cage-lab",
        title: "Induction: make the rotor field on demand",
        learningGoal: "See Faraday induction, the squirrel cage and why the rotor cannot catch up to the stator field.",
        visual: visual(
          "animated-field",
          "A rotating stator field sweeps past aluminium/copper bars joined by end rings. Relative motion induces current, then the cage develops its own field and force arrow.",
          "Play the field; pause with the rotor nearly caught up to watch induced current fade.",
          "Three frozen frames: field moving past cage, induced current loop, torque on the cage.",
        ),
        controls: [play("Runs the stator field past the squirrel cage."), { id: "relative-speed", label: "Relative speed", kind: "slider", consequence: "Reduces the changing field seen by the cage and fades induced current toward zero." }, next("Adds load and shows why slip is the operating principle.")],
        claimIds: ["induction-squirrel-cage", "motor-family-sync-async"],
        copy: {
          glance: "The induction rotor has no magnets and no external wires. It builds an electromagnet from the moving stator field.",
          why: "If it caught up perfectly, the field would stop changing relative to the cage. No induced voltage means no rotor current and no torque.",
          evidence: "The current loop is a simplified Faraday-law model of a squirrel-cage rotor.",
        },
        reducedMotionState: "Three-step induction storyboard linking rotating field, cage current and torque.",
      },
      {
        id: "induction-slip-heat-coast",
        title: "Slip makes torque—and heat",
        learningGoal: "See the self-regulating load relationship and the coast advantage of an induction rotor.",
        visual: visual(
          "thermal-map",
          "Increasing load widens the field/rotor speed gap, brightens cage current and adds rotor heat. Cutting stator power instantly removes the induced field and drag overlay.",
          "Increase load, then press 'cut power' to compare driven and coasting states.",
          "A static three-state panel: light load, heavy load, coasting with no rotor field.",
        ),
        controls: [{ id: "induction-load", label: "Load", kind: "slider", consequence: "Increases visible slip, induced current, torque and rotor heating." }, { id: "cut-induction-power", label: "Cut power", kind: "toggle", consequence: "Collapses rotor current and the induced field." }, next("Uses induction as one axle in a mixed drive layout.")],
        claimIds: ["induction-slip-range", "induction-rotor-loss-and-coast", "induction-ev-efficiency-tradeoff"],
        copy: {
          glance: "More load creates more slip, more induced current and more torque. It also makes rotor heat.",
          why: "That rotor loss is part of induction's EV efficiency trade-off. But when power is cut, its field disappears instead of continuing to drag.",
          evidence: "The stage shows a machine-specific relationship, not a universal slip percentage or range penalty.",
        },
        reducedMotionState: "Load-state triptych with a static heat map and a coasting cage without field lines.",
      },
      {
        id: "induction-mixed-axle",
        title: "Use each motor where it helps",
        learningGoal: "Understand a mixed-axle strategy without claiming one architecture wins every duty.",
        visual: visual(
          "vehicle-impact-map",
          "A dual-motor car assigns a PM drive to one axle and induction to the other; the reader toggles powered, coasting and all-wheel-drive states to see which field is active.",
          "Toggle drive mode and coast mode.",
          "A static transparent car with one PM axle and one induction axle, plus power-state arrows.",
        ),
        controls: [{ id: "drive-mode", label: "Drive / coast / AWD", kind: "select", consequence: "Activates the relevant axle and shows whether its rotor field persists." }, next("Replaces permanent magnets with a deliberately powered rotor winding.")],
        claimIds: ["induction-mixed-axle-use"],
        copy: {
          glance: "A vehicle can combine motor types across axles instead of making one choice everywhere.",
          why: "An induction axle can spin with little magnetic drag when unused, while a PM axle can carry the efficiency-focused duty.",
          evidence: "The named OEM examples and exact axle implementations remain evidence-lane records that need release-time checking.",
        },
        reducedMotionState: "Static dual-axle car showing PM and induction drive units.",
      },
      {
        id: "wound-field-lab",
        title: "Wound field: choose the rotor field",
        learningGoal: "See the direct PMSM-to-electromagnet substitution and its thermal cost.",
        visual: visual(
          "rotor-morph",
          "Buried magnets morph into copper rotor windings. An excitation slider changes rotor flux, and oil moves through a hollow shaft to a rotor heat zone.",
          "Morph magnets to windings, then adjust rotor excitation and switch rotor oil cooling on/off.",
          "A split PMSM/EESM rotor still with winding current, excitation dial and cooling path.",
        ),
        controls: [{ id: "rotor-excitation", label: "Rotor excitation", kind: "slider", consequence: "Changes the rotor field strength, including a fully off state." }, { id: "wound-oil", label: "Rotor oil cooling", kind: "toggle", consequence: "Moves heat out through the hollow shaft path." }, next("Compares a physical contact with a rotating transformer.")],
        claimIds: ["wound-field-principle", "wound-field-advantages-costs"],
        copy: {
          glance: "A wound-field motor is essentially a synchronous motor whose rotor field is made with copper instead of permanent magnets.",
          why: "You can turn that field down or off. The cost is a second electrical supply and heat inside a spinning rotor.",
          evidence: "The hollow-shaft cooling path is a representative engineering explanation, not a single OEM design.",
        },
        reducedMotionState: "PMSM and wound-field rotor comparison with static cooling path arrows.",
      },
      {
        id: "brushed-contactless-status",
        title: "Production EESM; emerging contactless excitation",
        learningGoal: "Separate already deployed externally excited synchronous motors from contactless concepts still on their own maturity timeline.",
        visual: visual(
          "evidence-lane",
          "Two parallel lanes compare production EESM examples, whose public sources do not establish identical rotor-current hardware, with a rotating-transformer contactless cutaway in an announced-development lane.",
          "Toggle production EESM and contactless EESM, then open the status evidence card for each named example.",
          "Static two-lane status diagram: production EESM with a transfer-hardware scope note, and contactless development with a rotating-transformer cutaway.",
        ),
        controls: [{ id: "excitation-method", label: "Production / contactless", kind: "toggle", consequence: "Switches the evidence lane and only the mechanism supported by its source." }, { id: "open-status", label: "Open status evidence", kind: "hotspot", consequence: "Reveals source date, qualifier and transfer-hardware scope." }, next("Removes both magnets and rotor windings.")],
        claimIds: ["wound-field-production-brushes", "contactless-wound-field-status", "vimag-volektra-same-company", "virtual-magnet-is-contactless-wound-field"],
        copy: {
          glance: "Production EESM is real. Contactless excitation is a different, newer engineering route.",
          why: "The retained public sources do not prove identical brush hardware in every production example. A rotating transformer, however, is a distinct contactless mechanism.",
          evidence: "Company relationship, product status and exact programme details remain bound to their source cards.",
        },
        reducedMotionState: "Two excitation cross-sections placed in their static evidence lanes.",
      },
      {
        id: "pure-synrm-lab",
        title: "SynRM: shape steel into an easy axis",
        learningGoal: "See reluctance torque with no magnets and no rotor windings, then expose its inverter consequence.",
        visual: visual(
          "force-vector-overlay",
          "A barrier-filled steel rotor seeks alignment with the stator field. A kVA overlay grows relative to wheel kW when the power-factor slider is reduced.",
          "Play the rotating field, then move the power-factor slider to see inverter-current burden.",
          "A static flux-barrier rotor with easy-axis arrows and a compact kW versus kVA comparison.",
        ),
        controls: [play("Rotates the stator field around the reluctance rotor."), { id: "power-factor", label: "Power factor", kind: "slider", consequence: "Increases the visible inverter kVA/cooling burden for the same wheel-kW marker." }, next("Adds small magnets back into the barriers.")],
        claimIds: ["synrm-principle", "synrm-inverter-power-factor"],
        copy: {
          glance: "The SynRM rotor is just shaped steel. It turns toward the easier magnetic path.",
          why: "That clean rotor avoids magnet supply and rotor copper loss, but the inverter can have to work harder for the same wheel power.",
          evidence: "The power-factor visual demonstrates direction of effect, not a universal inverter size calculation.",
        },
        reducedMotionState: "Static flux-barrier rotor with easy axis and kW/kVA relationship panel.",
      },
      {
        id: "pm-assisted-synrm-lab",
        title: "Put magnets back—carefully",
        learningGoal: "See why PM-assisted SynRM is a stacked configuration rather than a contradiction.",
        visual: visual(
          "rotor-morph",
          "Small magnets fade into the SynRM flux barriers. The torque mix shifts from reluctance-only to reluctance-plus-magnet while the same rotor geometry remains recognisable.",
          "Use the magnet-assist slider to grow or remove the embedded magnets.",
          "Before/after rotor cross-sections sharing the same flux barriers.",
        ),
        controls: [{ id: "magnet-assist", label: "Magnet assist", kind: "slider", consequence: "Adds embedded magnets and changes the visible torque contribution mix." }, next("Switches stator poles around a different reluctance rotor.")],
        claimIds: ["pm-assisted-synrm-stack", "stackable-technologies"],
        copy: {
          glance: "The textbook way to fix some pure-SynRM limits is to add magnets back into its barriers.",
          why: "That does not make the reluctance effect disappear. It makes the architecture a stack of both mechanisms.",
          evidence: "Tesla-style IPM-SynRM is kept in this stacked category, not used as evidence of a magnet-free motor.",
        },
        reducedMotionState: "Shared barrier rotor shown without and with embedded magnets.",
      },
      {
        id: "srm-aem-lab",
        title: "SRM: switch poles, then show the duty",
        learningGoal: "Understand switched reluctance, aluminium winding substitution, high speed and peak-versus-continuous output.",
        visual: visual(
          "animated-field",
          "Stator poles energise in sequence around a toothed rotor, producing discrete torque pulses. A speed dial raises rpm, while a time bar shows peak output falling to continuous capability.",
          "Play pole sequencing; raise speed; hold a power demand to reveal the continuous rating; toggle copper/aluminium winding material.",
          "Static pole-sequence storyboard plus a peak-to-continuous time bar and aluminium winding cross-section.",
        ),
        controls: [{ id: "srm-play", label: "Sequence poles", kind: "play", consequence: "Energises the next stator tooth and turns the rotor toward it." }, { id: "srm-duty", label: "Hold demand", kind: "slider", consequence: "Moves output from a short peak state toward a continuous state." }, { id: "winding-material", label: "Copper / aluminium", kind: "toggle", consequence: "Changes the stator-winding material and recyclability note without changing the torque principle." }, next("Changes the magnet chemistry instead of the torque principle.")],
        claimIds: ["aem-srm-principle", "aem-peak-continuous-gap"],
        copy: {
          glance: "SRM turns a toothed steel rotor by switching stator poles in sequence. AEM also substitutes aluminium for copper windings.",
          why: "A headline peak number does not say how long the machine can hold it. The continuous-to-peak gap must be visible.",
          evidence: "The reported AEM numbers and development status are verification-required and are always paired in the evidence drawer.",
        },
        reducedMotionState: "Four-pole static sequence, aluminium-winding cross-section, and peak/continuous comparison bar.",
      },
    ],
  },
  {
    id: "change-the-magnet-or-geometry",
    number: 6,
    title: "Change the magnet—or the geometry",
    premise: "Chemistry, geometry and torque principle are different controls.",
    steps: [
      {
        id: "ferrite-material-not-architecture",
        title: "Ferrite changes the magnet, not the motor family",
        learningGoal: "Keep ferrite on the chemistry layer while showing why its lower magnetic output changes motor design.",
        visual: visual(
          "before-after-comparison",
          "An NdFeB rotor swaps only its magnet blocks for ferrite. Field lines thin; a geometry dial then compensates by increasing diameter, length or speed.",
          "Swap the magnet chemistry, then choose a compensation path.",
          "A same-architecture rotor before/after with a size-and-speed trade-off mini map.",
        ),
        controls: [{ id: "magnet-swap", label: "NdFeB / ferrite", kind: "toggle", consequence: "Changes the magnet blocks and visible flux density without changing the torque-principle label." }, { id: "ferrite-compensation", label: "Compensate with", kind: "select", consequence: "Expands diameter, length or speed rather than pretending the swap is free." }, next("Rotates the flux direction to change packaging.")],
        claimIds: ["ferrite-is-chemistry", "ferrite-remanence-energy-product", "ferrite-cold-constraint"],
        copy: {
          glance: "A ferrite PMSM is still a PMSM. The material changed; the torque principle did not.",
          why: "Weaker remanence and energy product mean the motor usually pays somewhere else—in size, speed or geometry. Cold behaviour also belongs in the story.",
          evidence: "The generic ferrite ratios are marked as verification-required and never relabelled as 'field strength' or universal coercivity.",
        },
        reducedMotionState: "Same rotor with NdFeB and ferrite magnet blocks, plus a static size/speed compensation map.",
      },
      {
        id: "axial-flux-geometry",
        title: "Axial flux is a shape choice",
        learningGoal: "See radial and axial flux as geometry choices available to more than one magnet chemistry.",
        visual: visual(
          "rotor-morph",
          "A radial-flux cylinder turns into a disc-like axial-flux layout while a chemistry selector remains independently available.",
          "Morph radial to axial, then independently switch NdFeB and ferrite magnet tiles.",
          "Radial and axial cross-sections with the flux direction arrows clearly labelled.",
        ),
        controls: [{ id: "geometry-morph", label: "Radial / axial", kind: "toggle", consequence: "Changes flux direction and package shape while preserving the independently selected chemistry." }, { id: "geometry-chemistry", label: "Magnet chemistry", kind: "toggle", consequence: "Changes material tiles without redefining the geometry." }, next("Keeps speed next to power in a ferrite prototype comparison.")],
        claimIds: ["axial-flux-is-geometry", "stackable-technologies"],
        copy: {
          glance: "Axial flux describes where the field travels. It is not another magnet material.",
          why: "A designer can pair axial geometry with ferrite, NdFeB or another material. The interface must let those decisions stack.",
          evidence: "This is a topology comparison, not a claim that axial flux automatically erases a material trade-off.",
        },
        reducedMotionState: "Static radial and axial cross-sections with independent chemistry chips.",
      },
      {
        id: "proterial-power-speed",
        title: "Power needs its operating condition",
        learningGoal: "Read a prototype power comparison with speed and baseline conditions rather than as an isolated headline.",
        visual: visual(
          "matrix",
          "A matched prototype card locks each power bar to its rpm: ferrite prototype and NdFeB baseline move together when the 'show speed' layer is toggled.",
          "Toggle speed labels off and on; the interface prevents the comparison from remaining in an ambiguous power-only state.",
          "Two aligned power-and-rpm bars with a visible condition lock icon.",
        ),
        controls: [{ id: "show-operating-condition", label: "Show speed", kind: "toggle", consequence: "Reveals the rpm attached to each power figure; the comparison label changes from incomplete to interpretable." }, next("Separates iron-nitride strength from permanent-magnet hardness.")],
        claimIds: ["proterial-power-speed-pair"],
        copy: {
          glance: "102 kW at 15,000 rpm is not the same operating point as 110 kW at 10,000 rpm.",
          why: "Power numbers only become comparable when speed, duty and baseline are on stage with them.",
          evidence: "The records are prototype/company-material claims and are marked for primary-source verification.",
        },
        reducedMotionState: "Aligned two-row comparison showing kW and rpm together.",
      },
      {
        id: "iron-nitride-property-board",
        title: "Do not confuse saturation with a usable magnet",
        learningGoal: "Compare saturation, remanence, coercivity, energy product and thermal margin as separate properties.",
        visual: visual(
          "matrix",
          "A material board has five independent dials. Selecting a property lights only its physical meaning; an attempted 'strongest' summary fractures into the full set of constraints.",
          "Click each property, then press 'can it be a drop-in?' to reveal the missing tests.",
          "A static five-column material ledger with no single composite winner badge.",
        ),
        controls: [{ id: "property-select", label: "Select property", kind: "select", consequence: "Highlights its distinct physical role rather than blending the metrics." }, { id: "drop-in-check", label: "Check drop-in claim", kind: "toggle", consequence: "Expands the required-property checklist and thermal qualification warning." }, next("Shows why a variable-flux prototype may value a different property.")],
        claimIds: ["iron-nitride-is-chemistry", "iron-nitride-saturation-not-hardness", "niron-material-range", "iron-nitride-thermal-margin"],
        copy: {
          glance: "A high saturation figure is not the same as a high-coercivity, high-energy-product traction magnet.",
          why: "A permanent magnet needs both field strength and a reliable lock on that field, across a real thermal duty cycle.",
          evidence: "Niron material figures and thermal range are kept as verification-required material records—not vehicle performance claims.",
        },
        reducedMotionState: "Five-property static matrix with a visible 'not one number' conclusion.",
      },
      {
        id: "matter-variable-flux",
        title: "When weaker locking is useful",
        learningGoal: "Understand why a variable-flux motor can value deliberate weakening and remagnetisation.",
        visual: visual(
          "parameter-slider",
          "A variable-flux rotor cycles between strong low-speed flux and weakened high-speed flux; a conventional permanent-magnet reminder card shows why low coercivity is normally a constraint.",
          "Move the speed slider and enable variable-flux control to alter the magnet state.",
          "Two static operating points: low-speed torque and high-speed weakened-flux mode.",
        ),
        controls: [{ id: "variable-flux-speed", label: "Motor speed", kind: "slider", consequence: "Moves the motor between low-speed flux and high-speed field-management states." }, { id: "variable-flux-control", label: "Variable-flux control", kind: "toggle", consequence: "Shows deliberate field adjustment rather than accidental demagnetisation." }, next("Builds combinations instead of putting them in exclusive boxes.")],
        claimIds: ["matter-variable-flux-fit"],
        copy: {
          glance: "A property that is a weakness for a fixed permanent magnet can be useful when the machine wants to vary its flux deliberately.",
          why: "The question is not whether low coercivity is simply good or bad. It is whether the architecture can control it safely for the intended job.",
          evidence: "Matter/Niron work is presented as a verification-required prototype relationship.",
        },
        reducedMotionState: "Low-speed and high-speed variable-flux states beside a fixed-magnet comparison.",
      },
      {
        id: "stackable-motor-builder",
        title: "Build a motor without category errors",
        learningGoal: "Compose torque principle, excitation, magnet chemistry, geometry and winding material independently.",
        visual: visual(
          "configuration-builder",
          "A live motor cross-section rebuilds as the reader selects independent layers: torque principle, rotor excitation, magnet chemistry, geometry and winding material. A market/status footer changes separately.",
          "Choose one option in each layer; load named combinations such as Tesla IPM-SynRM, Conifer ferrite-plus-axial, and AEM aluminium SRM.",
          "A static configuration card with five independent rows and the resulting cross-section.",
        ),
        controls: [{ id: "motor-builder", label: "Configure motor", kind: "select", consequence: "Updates only the chosen layer and keeps the others visibly independent." }, { id: "load-example", label: "Load named example", kind: "select", consequence: "Loads a sourced stack and opens its caveat/evidence record." }, next("Returns to the vehicle to measure what each change costs.")],
        claimIds: ["stackable-technologies", "ferrite-is-chemistry", "axial-flux-is-geometry", "virtual-magnet-is-contactless-wound-field"],
        copy: {
          glance: "A motor is a stack of choices, not one label.",
          why: "This builder prevents the report's category errors: ferrite is chemistry, axial flux is geometry, and contactless excitation is a way to power a wound rotor.",
          evidence: "Named examples expose their maturity and caveat record rather than becoming endorsements.",
        },
        reducedMotionState: "Five-layer static configuration form with three named example outputs.",
      },
    ],
  },
  {
    id: "what-the-vehicle-must-change",
    number: 7,
    title: "What the vehicle must change",
    premise: "A motor swap is usually a drive-unit redesign, not a new car from scratch.",
    steps: [
      {
        id: "vehicle-survivors-and-changes",
        title: "What survives the swap?",
        learningGoal: "Separate vehicle systems often retained from drive-unit systems that may need redesign.",
        visual: visual(
          "vehicle-impact-map",
          "A full car holds body, crash structure, interior, battery and suspension in neutral grey while the drive-unit region changes colour as a motor architecture is selected.",
          "Select reduced-HREE PM, ferrite PM, induction, wound field, SynRM or SRM.",
          "A static car heat-map for each selected architecture with unchanged and changed components clearly keyed.",
        ),
        controls: [{ id: "swap-architecture", label: "Choose architecture", kind: "select", consequence: "Recolours only the inverter, motor, cooling, package and software regions that must change." }, next("Opens the drive unit to identify the work.")],
        claimIds: ["vehicle-swap-burden", "reduced-hree-near-drop-in"],
        copy: {
          glance: "The body, cabin, battery and suspension can often remain. The drive unit cannot be treated as unchanged.",
          why: "The scale of the engineering job depends sharply on whether you changed only heavy-rare-earth use, a magnet chemistry or the whole rotor-field architecture.",
          evidence: "This is a comparative integration model; each programme requires its own package and safety review.",
        },
        reducedMotionState: "Static full-car map with neutral retained systems and one selected drive-unit change footprint.",
      },
      {
        id: "inverter-and-cooling-burden",
        title: "The change is inside the drive unit",
        learningGoal: "Connect architecture choices to inverter, excitation, cooling and package changes.",
        visual: visual(
          "exploded-model",
          "The same drive unit opens for each selected motor. Wound field adds a rotor supply and hollow-shaft cooling; SynRM grows the inverter-current/cooling overlay; induction shifts heat into the rotor.",
          "Use the architecture selector and tap inverter, rotor supply, coolant loop or controls to compare.",
          "A static exploded drive unit for each architecture with changed modules highlighted.",
        ),
        controls: [{ id: "drive-unit-compare", label: "Compare drive unit", kind: "select", consequence: "Swaps only the architecture-dependent modules, leaving the common functions ghosted for comparison." }, { id: "change-hotspots", label: "Why changed?", kind: "hotspot", consequence: "Explains the physical cause of each highlighted redesign item." }, next("Ranks those options by integration burden.")],
        claimIds: ["vehicle-swap-burden", "wound-field-advantages-costs", "synrm-inverter-power-factor", "induction-ev-efficiency-tradeoff"],
        copy: {
          glance: "Different rotors move the problem to different places: power supply, inverter sizing, rotor heat, cooling, package or controls.",
          why: "A PMSM mostly puts losses where a stator water jacket can reach. A wound field puts important heat on a spinning rotor. A pure SynRM can change inverter demand.",
          evidence: "The visual models causal architecture changes rather than quoting unsupported universal component dimensions.",
        },
        reducedMotionState: "Selected-architecture exploded drive unit with static changed-module callouts.",
      },
      {
        id: "swap-burden-spectrum",
        title: "From material adjustment to platform change",
        learningGoal: "Compare the relative vehicle integration burden without calling every alternative a drop-in replacement.",
        visual: visual(
          "matrix",
          "Six routes sit on a swap-burden spectrum. Each route paints a row across inverter, cooling, package, controls, safety case and validation columns.",
          "Select a route or sort by one system to see why its burden moves.",
          "Static change-matrix with a clear near-drop-in-to-full-redesign axis.",
        ),
        controls: [{ id: "burden-select", label: "Select route", kind: "select", consequence: "Highlights every affected subsystem for that route." }, { id: "burden-sort", label: "Sort by subsystem", kind: "select", consequence: "Reorders the matrix around inverter, cooling, package or controls." }, next("Puts the engineering work on a validation timeline.")],
        claimIds: ["reduced-hree-near-drop-in", "vehicle-swap-burden"],
        copy: {
          glance: "Dy/Tb reduction is not the same size of change as a wound-field redesign.",
          why: "A useful map says what really changes. It does not call ferrite, induction, SynRM and wound field all 'true drop-ins' because the chassis shell can survive.",
          evidence: "The spectrum is comparative and qualitative; it directs the reader to the system-specific evidence cards.",
        },
        reducedMotionState: "Static six-route impact matrix with explicit near-drop-in and full-redesign endpoints.",
      },
      {
        id: "validation-runway",
        title: "The calendar is part of the technology",
        learningGoal: "See validation, calibration and homologation as a real adoption constraint.",
        visual: visual(
          "timeline",
          "A validation runway runs through package design, inverter/control development, thermal/NVH work, safety case, durability testing and homologation. The selected route changes how many workstreams light up.",
          "Select a motor route and scrub across the programme timeline.",
          "A static multi-lane programme map with design, validation and homologation gates but no universal duration.",
        ),
        controls: [{ id: "validation-route", label: "Choose route", kind: "select", consequence: "Activates the workstreams that the route adds or intensifies." }, { id: "validation-time", label: "Programme time", kind: "scrub", consequence: "Moves a marker through design, validation and homologation gates." }, next("Places two motor types on two axles as a compromise.")],
        claimIds: ["vehicle-validation-window", "vehicle-swap-burden"],
        copy: {
          glance: "A new motor architecture is also a validation programme.",
          why: "Cooling, control calibration, NVH, functional safety and homologation take time even when the rest of the vehicle can remain familiar.",
          evidence: "The visual deliberately has no universal duration. Actual programmes depend on platform reuse, architecture and regulatory scope.",
        },
        reducedMotionState: "Static programme timeline with labelled workstreams and an illustrative duration bracket.",
      },
      {
        id: "mixed-axle-revisit",
        title: "Do not force one answer everywhere",
        learningGoal: "Reinforce that an OEM can stage technologies by axle and duty cycle.",
        visual: visual(
          "vehicle-impact-map",
          "A vehicle planner lets the reader assign PM, induction or wound-field drive units to front and rear axles; each choice changes coast drag, rotor supply and cooling overlays.",
          "Choose front and rear axle architectures and switch among city, motorway and coast modes.",
          "Three static vehicle states: city, motorway and coast, with axle roles labelled.",
        ),
        controls: [{ id: "front-axle", label: "Front axle", kind: "select", consequence: "Loads the chosen architecture and its physical overlays at the front." }, { id: "rear-axle", label: "Rear axle", kind: "select", consequence: "Loads the chosen architecture and its physical overlays at the rear." }, { id: "duty-mode", label: "Duty mode", kind: "select", consequence: "Shows different active-field and efficiency priorities." }, next("Moves from physics to market evidence.")],
        claimIds: ["induction-mixed-axle-use", "vehicle-swap-burden"],
        copy: {
          glance: "An OEM can mix motor types across axles and operating modes.",
          why: "That may be more realistic than waiting for one architecture to match every duty at once.",
          evidence: "Named axle examples are kept in the evidence lane, with current implementation status marked for verification.",
        },
        reducedMotionState: "Static two-axle selector showing a PM rear and induction front example.",
      },
    ],
  },
  {
    id: "what-is-real-and-indias-opening",
    number: 8,
    title: "What is real—and India’s opening",
    premise: "Market, maturity and evidence decide what a technically possible idea means today.",
    steps: [
      {
        id: "two-markets-switch",
        title: "Do not mix the markets",
        learningGoal: "Separate EV traction's rare-earth substitution problem from industry's induction-efficiency problem.",
        visual: visual(
          "matrix",
          "A market switch changes the incumbent, reason to change, performance constraint and company examples: NdFeB PMSM/supply exposure for EV traction; induction/efficiency regulation for industrial drives.",
          "Toggle EV traction, light mobility, industrial drive and appliance lanes.",
          "A four-lane static matrix with a different incumbent and reason-to-change in each lane.",
        ),
        controls: [{ id: "market-lane", label: "Choose market", kind: "select", consequence: "Rewrites the comparison context and filters examples without moving them between markets." }, next("Places company records on dated evidence lanes.")],
        claimIds: ["industrial-induction-incumbent", "named-company-corrections"],
        copy: {
          glance: "EV traction and industrial motors start from different incumbents and solve different problems.",
          why: "An industrial SynRM can be an efficiency replacement for an induction motor even though it has little to do with replacing rare-earth magnets in an EV.",
          evidence: "Company cards are filtered by declared market to stop appliance, industrial and vehicle evidence being blended.",
        },
        reducedMotionState: "Static side-by-side EV traction and industrial-drive market cards with distinct incumbents.",
      },
      {
        id: "evidence-maturity-lanes",
        title: "Status is not a single word",
        learningGoal: "Read production, industrial product, vehicle pilot, announced development, prototype and material scale-up as distinct evidence states.",
        visual: visual(
          "evidence-lane",
          "Company/product tokens occupy dated lanes: production vehicle, industrial product, vehicle pilot, announced development, prototype and materials scale-up. Clicking a token opens its architecture stack and evidence caveat.",
          "Filter by market or architecture; open a token to inspect its date, qualifier, source type and verification status.",
          "A static six-lane evidence board with representative named tokens and a clear 'needs verification' treatment.",
        ),
        controls: [{ id: "evidence-filter", label: "Filter records", kind: "select", consequence: "Filters by market and configuration without changing a record's maturity lane." }, { id: "evidence-token", label: "Open record", kind: "hotspot", consequence: "Shows source, date, qualifier, caveat and configuration axes." }, next("Tests claims that can be misleading without their operating conditions.")],
        claimIds: ["wound-field-production-brushes", "contactless-wound-field-status", "ibee-target-status", "aem-peak-continuous-gap", "proterial-power-speed-pair", "matter-variable-flux-fit"],
        copy: {
          glance: "A production vehicle, a target, a pilot, a prototype and material scale-up are not interchangeable proof.",
          why: "The visual gives status as much prominence as performance, so the reader can see what is actually shipping and what still needs validation.",
          evidence: "Every named record carries a source type, date, market, maturity, qualifier, caveat and verification flag.",
        },
        reducedMotionState: "Static six-lane evidence board with named tokens and legend.",
      },
      {
        id: "claim-condition-checker",
        title: "Make the condition visible",
        learningGoal: "Learn to reject decontextualised power, efficiency, funding and location claims.",
        visual: visual(
          "before-after-comparison",
          "A claim card begins as a misleading headline. Turning on condition layers adds peak/continuous, speed, target date, market, source and caveat until it becomes interpretable.",
          "Toggle the required evidence layers one by one; incomplete cards visibly remain unapproved.",
          "A static incomplete-versus-complete claim card, with missing provenance slots clearly shown.",
        ),
        controls: [{ id: "condition-layer", label: "Add condition", kind: "toggle", consequence: "Fills one required provenance field and updates the claim's confidence state." }, next("Maps the capability stack India can build.")],
        claimIds: ["proterial-power-speed-pair", "aem-peak-continuous-gap", "renault-efficiency-condition", "ibee-target-status", "named-company-corrections"],
        copy: {
          glance: "A number without a condition can make a prototype look like parity or a target look like a product.",
          why: "Power needs speed and duty. Efficiency needs an operating condition. A company claim needs market, maturity, date and source.",
          evidence: "The content system rejects quantitative records missing the provenance needed to interpret them.",
        },
        reducedMotionState: "Static incomplete and complete claim-card comparison.",
      },
      {
        id: "india-capability-stack",
        title: "The opening is a capability stack",
        learningGoal: "See the opportunity as a connected industrial system rather than a single rare-earth-free motor announcement.",
        visual: visual(
          "capability-stack",
          "An India capability stack assembles from steel and laminations through windings, inverter electronics, controls, cooling, testing and manufacturing. Selecting an architecture lights the capabilities it exercises.",
          "Select an architecture, then click a capability to trace its inputs and downstream dependencies.",
          "A static vertically connected capability stack with architecture-specific highlight paths.",
        ),
        controls: [{ id: "capability-architecture", label: "Choose architecture", kind: "select", consequence: "Highlights the domestic capabilities the route demands." }, { id: "capability-node", label: "Inspect capability", kind: "hotspot", consequence: "Traces its upstream inputs and downstream vehicle/manufacturing consequence." }, next("Closes on a realistic rather than premature market conclusion.")],
        claimIds: ["india-opportunity-capabilities", "market-rare-earth-free-share-small", "vehicle-swap-burden"],
        copy: {
          glance: "India's opening is the ability to build a whole motor-and-drive capability stack while the market is still early.",
          why: "Different alternatives shift value into different places: steel, winding, power electronics, software, cooling, testing and manufacturing all become part of the answer.",
          evidence: "This is a strategic interpretation of the supplied due diligence, not a forecast of guaranteed market share.",
        },
        reducedMotionState: "Static linked capability stack with the selected architecture's path highlighted.",
      },
      {
        id: "final-decision-map",
        title: "Choose the question before the technology",
        learningGoal: "Synthesize the full flow without declaring one universal winner.",
        visual: visual(
          "configuration-builder",
          "A decision map begins with the problem—reduce Dy/Tb exposure now, remove all rare earths, optimise high-speed control, replace industrial induction, or explore new material—and routes to mechanisms, vehicle burden, maturity and evidence.",
          "Choose a starting problem; the map animates the relevant physical mechanism, vehicle impact and evidence lane together.",
          "A static decision map with five problem-entry nodes and clearly labelled routes.",
        ),
        controls: [{ id: "decision-question", label: "Start with a question", kind: "select", consequence: "Highlights a defensible route and the caveats that remain." }, back("Returns to any earlier chapter without a long scroll."), { id: "replay-journey", label: "Replay journey", kind: "play", consequence: "Cycles through the eight chapter keyframes with captions; it is always pausable." }],
        claimIds: ["reduced-hree-near-drop-in", "wound-field-advantages-costs", "industrial-induction-incumbent", "iron-nitride-saturation-not-hardness", "india-opportunity-capabilities"],
        copy: {
          glance: "There is no single post-rare-earth motor. There are different problems, mechanisms, time horizons and integration burdens.",
          why: "Start with the question you need to solve. Then inspect the machine, the material, the vehicle change and the evidence state together.",
          evidence: "Research and visualization by Tannmay Kumarr Baid and Shobhankita Reddy.",
        },
        reducedMotionState: "Static decision map with all five question-entry routes visible.",
      },
    ],
  },
] as const satisfies readonly RawChapterManifest[];

export const chapters: readonly ChapterManifest[] = rawChapters.map((chapter) => ({
  ...chapter,
  steps: chapter.steps.map((step) => {
    const learnerQuestion = learnerQuestions[step.id];
    if (!learnerQuestion) {
      throw new Error(`Missing learner question for content step: ${step.id}`);
    }
    return {
      ...step,
      learnerQuestion,
      placement: mainStepIds.has(step.id) ? "main" : "optional-deep-dive",
    };
  }),
}));
