import type { Claim } from "./schema.ts";

const dueDiligence = "due-diligence-notes";

type RawClaim = Omit<Claim, "evidenceStatus" | "renderingPolicy"> &
  Partial<Pick<Claim, "evidenceStatus" | "renderingPolicy" | "evidenceRecordId">>;

/**
 * Atomic editorial claims. The UI can show a claim only after carrying its
 * provenance, scope, and caveat with it into the evidence drawer.
 */
const rawClaims = [
  {
    id: "market-rare-earth-free-share-small",
    statement:
      "Rare-earth-free traction remains an emerging, unevenly disclosed segment; no qualifying source in the launch audit supports a precise 5% share.",
    sourceIds: ["ev-magnet-materials-review"],
    sourceType: "primary",
    evidenceStatus: "unverified",
    renderingPolicy: "hide",
    evidenceRecordId: "market.rare_earth_free_share",
    date: "2024-07-02",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "share of the current EV traction-motor market; no qualifying denominator found",
    caveat:
      "Do not display a 5% market-share value. A qualitative emerging-segment visual is permitted only when labelled illustrative.",
    needsVerification: true,
  },
  {
    id: "pmsm-stator-three-phase-field",
    statement:
      "Three stator winding groups, supplied with AC currents offset by one third of a cycle, create a magnetic field that appears to rotate around the stator bore.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "idealised three-phase traction-motor teaching model",
    quantitative: {
      label: "phase separation",
      value: 120,
      unit: "electrical degrees",
      denominator: "three balanced phase currents in the teaching model",
    },
    caveat: "The animation is a simplified field model, not a finite-element simulation.",
    needsVerification: false,
  },
  {
    id: "pmsm-synchronous-torque-angle",
    statement:
      "In a PMSM the rotor follows the rotating stator field at the same electrical speed; load appears as a torque angle between the two fields, not induction-style slip.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "idealised synchronous-machine teaching model",
    caveat: "The visual isolates the core synchronous relationship from control-loop detail.",
    needsVerification: false,
  },
  {
    id: "ipm-magnets-buried",
    statement:
      "Interior permanent magnets are mechanically retained by the rotor at high speed and their placement creates unequal magnetic paths through steel and magnet material.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "representative IPM rotor cross-section",
    caveat: "Rotor geometry differs by motor design; the visual shows the mechanism, not one OEM drawing.",
    needsVerification: false,
  },
  {
    id: "ipm-reluctance-torque",
    statement:
      "The magnetically easier steel path in an IPM rotor also produces reluctance torque, so an IPM-SynRM combines permanent-magnet and synchronous-reluctance effects.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "representative IPM-SynRM rotor geometry",
    conflict:
      "The original report treats reluctance as a wholly separate branch; the due diligence identifies it as a mainstream contribution inside IPM-SynRM machines.",
    needsVerification: false,
  },
  {
    id: "magnet-remanence-definition",
    statement:
      "Remanence is the magnetic flux a magnet retains with no external field helping it.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "plain-language magnet-property teaching model",
    needsVerification: false,
  },
  {
    id: "magnet-coercivity-definition",
    statement:
      "Coercivity is a magnet's resistance to an opposing field that tries to reverse its magnetisation.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "plain-language magnet-property teaching model",
    needsVerification: false,
  },
  {
    id: "ndfeb-division-of-labour",
    statement:
      "In NdFeB, iron contributes much of the magnetic strength while rare-earth chemistry helps make the magnetisation hard to reverse.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "qualitative explanation of NdFeB magnetic roles",
    caveat: "This is a teaching simplification of the alloy's microphysics.",
    needsVerification: false,
  },
  {
    id: "traction-temperature-range",
    statement:
      "Magnet temperature and opposing field jointly affect demagnetisation margin, but no universal traction-magnet temperature band is used in the public visual.",
    sourceIds: [dueDiligence],
    sourceType: "due-diligence",
    evidenceStatus: "unverified",
    renderingPolicy: "hide",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "representative traction-motor thermal condition, not every motor",
    caveat: "Actual magnet temperature, winding temperature and transient peaks differ by vehicle and cooling design. Do not render 150–180°C as a generic fact.",
    needsVerification: true,
  },
  {
    id: "coercivity-temperature-sensitivity",
    statement:
      "Coercivity falls with elevated temperature, increasing demagnetisation risk under opposing fields; its slope is grade-specific.",
    sourceIds: [dueDiligence],
    sourceType: "due-diligence",
    evidenceStatus: "unverified",
    renderingPolicy: "hide",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "specific magnet grade and temperature interval not supplied",
    caveat: "Do not show an unsupported universal 0.5% per °C slope. Temperature coefficients vary materially by grade.",
    needsVerification: true,
  },
  {
    id: "dy-tb-thermal-role",
    statement:
      "Dysprosium and terbium are used to preserve coercivity at elevated temperature; they do not cool the magnet.",
    sourceIds: ["ndfeb-coercivity-review"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "magnets.dy_tb_role",
    date: "2021-06-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "high-temperature NdFeB traction-magnet use",
    conflict:
      "Corrects wording that implies Dy/Tb are added so a motor or magnet does not get hot.",
    needsVerification: false,
  },
  {
    id: "dy-strength-tradeoff",
    statement:
      "Adding more dysprosium improves thermal resistance to reversal but can reduce magnetic strength, so the useful design question is where the heavy rare earth is placed.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "qualitative alloy trade-off",
    needsVerification: false,
  },
  {
    id: "gbd-grain-shell",
    statement:
      "Grain-boundary diffusion concentrates dysprosium near grain boundaries, where reversal can nucleate, while leaving more of the grain interior as NdFeB.",
    sourceIds: ["ornl-gbd-coating"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "magnets.gbd",
    date: "2015-12-01",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "grain-boundary-diffused NdFeB magnet microstructure",
    needsVerification: false,
  },
  {
    id: "illustrative-magnet-composition",
    statement:
      "NdFeB grades use different alloy recipes and heavy-rare-earth strategies; the visual deliberately avoids one universal mass recipe.",
    sourceIds: [dueDiligence],
    sourceType: "due-diligence",
    evidenceStatus: "unverified",
    renderingPolicy: "hide",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "illustrative traction-magnet composition by weight, not a universal grade",
    caveat: "Composition varies by grade, temperature requirement and diffusion process; do not publish the due-diligence recipe as a universal alloy.",
    needsVerification: true,
  },
  {
    id: "smco-temperature-position",
    statement:
      "SmCo is a qualified, more expensive permanent-magnet route for some higher-temperature applications; it is not a universal comparison or product recommendation.",
    sourceIds: [dueDiligence],
    sourceType: "due-diligence",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "high-temperature permanent-magnet applications",
    needsVerification: true,
  },
  {
    id: "hree-controls-distinct-from-ndpr",
    statement:
      "China's 4 April 2025 notice imposed export controls on specified medium and heavy rare-earth items; Dy/Tb-related magnet materials were covered, while Nd and Pr were not named in that specific notice.",
    sourceIds: ["china-april-2025-controls"],
    sourceType: "primary",
    evidenceStatus: "qualified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "supply.ndpr_not_listed_in_notice",
    date: "2025-04-04",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "items covered by the cited 2025 export controls",
    caveat: "Show this as a dated licence-control notice, not a blanket ban or a permanent claim that Nd/Pr are secure.",
    needsVerification: true,
  },
  {
    id: "reduced-hree-near-drop-in",
    statement:
      "Reducing dysprosium/terbium through cooling or grain-boundary diffusion can retain the existing permanent-magnet architecture, unlike a full motor-architecture change.",
    sourceIds: [dueDiligence],
    sourceType: "due-diligence",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "existing NdFeB PMSM drive-unit architecture",
    caveat: "Motor-specific validation is still required; 'near-drop-in' does not mean no validation.",
    needsVerification: true,
  },
  {
    id: "proterial-hree-free-ndfeb",
    statement:
      "Proterial announced heavy-rare-earth-free NdFeB materials intended for EV drive-motor applications in July 2025; this removes Dy/Tb, not Nd/Pr.",
    sourceIds: ["proterial-hree-free"],
    sourceType: "company-claim",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "supply.proterial_hree_free",
    date: "2025-07-22",
    market: "ev-traction",
    maturity: "announced-development",
    qualifier: "prototype",
    denominator: "Proterial material announcement for EV drive-motor applications",
    caveat: "Label this HREE-free NdFeB, not rare-earth-free; retain its pre-production/research-facility context.",
    needsVerification: false,
  },
  {
    id: "rotor-oil-cooling-reduces-hree",
    statement:
      "Audi says direct oil cooling in the Q6 e-tron keeps stator windings and rotor permanent magnets in their optimum temperature range.",
    sourceIds: ["audi-q6-oil-cooling"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "cooling.audi_q6_direct_oil",
    date: "2024-06-01",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "traction PMSM thermal design",
    caveat: "This is thermal-management evidence, not proof that Audi removed Dy/Tb or reached a particular rotor temperature.",
    needsVerification: false,
  },
  {
    id: "back-emf-constraint",
    statement:
      "A permanent-magnet rotor generates back-EMF as speed rises; when that voltage approaches the available DC bus, the inverter must weaken the magnet field to keep increasing speed.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "idealised permanent-magnet traction-drive speed sweep",
    needsVerification: false,
  },
  {
    id: "field-weakening-no-torque",
    statement:
      "Field weakening adds current that bucks fixed permanent-magnet flux at high speed, increasing reactive-current burden and ohmic losses.",
    sourceIds: ["doe-wound-field-report"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "pmsm.field_weakening",
    date: "2017-03-31",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "idealised PMSM high-speed control explanation",
    caveat: "Do not state that all field-weakening current produces zero torque at every operating point; the visual isolates the added burden.",
    needsVerification: false,
  },
  {
    id: "pmsm-inverter-failure-risk",
    statement:
      "Always-on permanent-magnet flux creates inverter-fault safety concerns because the rotor field cannot be commanded off.",
    sourceIds: ["doe-wound-field-report"],
    sourceType: "primary",
    evidenceStatus: "qualified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "pmsm.inverter_fault",
    date: "2017-03-31",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "PMSM drive fault at vehicle speed",
    caveat: "Do not imply a universal braking-torque or DC-link-voltage outcome without a specific inverter/fault-topology source.",
    needsVerification: false,
  },
  {
    id: "motor-family-sync-async",
    statement:
      "Synchronous traction machines keep rotor field and stator field in step; induction machines need a small speed difference, called slip, to induce rotor current.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "motor-family teaching classification",
    needsVerification: false,
  },
  {
    id: "induction-squirrel-cage",
    statement:
      "An induction rotor uses conductive bars shorted by end rings: a squirrel cage. The changing stator field induces current in that cage, and the induced current creates torque.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "representative squirrel-cage induction motor",
    needsVerification: false,
  },
  {
    id: "induction-slip-range",
    statement:
      "An induction rotor must run behind the stator field so relative motion can induce its rotor current; the actual slip is machine- and load-specific.",
    sourceIds: ["bmw-gen6-asm"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "induction.slip_and_cage",
    date: "2025-02-19",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "induction-machine relative-speed relationship; no universal percentage used",
    caveat: "Do not display a generic 1–3% slip number without one machine and load condition.",
    needsVerification: false,
  },
  {
    id: "induction-rotor-loss-and-coast",
    statement:
      "Induction rotor current creates resistive heat, especially away from its best operating region, but it also dies when power is cut so the rotor field and magnetic drag collapse.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "comparative induction-versus-permanent-magnet teaching model",
    needsVerification: false,
  },
  {
    id: "induction-ev-efficiency-tradeoff",
    statement:
      "Induction traction trades an induced, lossy rotor field against the ability to remove that field during coasting; any efficiency or range delta is vehicle- and duty-cycle-specific.",
    sourceIds: [dueDiligence],
    sourceType: "due-diligence",
    evidenceStatus: "unverified",
    renderingPolicy: "hide",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "EV traction use over an unspecified drive cycle",
    caveat: "Do not display a generic 3% efficiency or range penalty; it depends on vehicle, drive cycle and axle use.",
    needsVerification: true,
  },
  {
    id: "induction-mixed-axle-use",
    statement:
      "Audi's Q6 e-tron uses an ASM at the front axle for maximum performance and a rear PSM, while BMW's Gen6 xDrive concept retains rear EESM and adds ASM at the front.",
    sourceIds: ["audi-q6-oil-cooling", "bmw-gen6-asm"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "induction.mixed_axle",
    date: "2025-02-19",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "specific dual-motor EV layouts named in the due diligence",
    caveat: "Attribute each layout to its named vehicle/platform; do not generalise it to all Audi or BMW models.",
    needsVerification: false,
  },
  {
    id: "wound-field-principle",
    statement:
      "A wound-field synchronous motor deliberately sends current through rotor windings, making the rotor an adjustable electromagnet that remains synchronous with the stator field.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "representative electrically excited synchronous motor",
    needsVerification: false,
  },
  {
    id: "wound-field-advantages-costs",
    statement:
      "Wound-field machines remove permanent magnets and can turn rotor flux down or off, but add rotor excitation power, rotor heat, cooling hardware and control complexity.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "architecture-level comparison with PMSM",
    needsVerification: false,
  },
  {
    id: "wound-field-production-brushes",
    statement:
      "Electrically excited synchronous traction motors are not merely experimental: Renault mass-sold EESM from 2012, Nissan states the 2022 Ariya has a magnet-free EESM, and BMW uses EESM in Gen5/Gen6.",
    sourceIds: ["renault-eesm", "nissan-ariya", "bmw-gen6-asm"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "eesm.production_renault_nissan_bmw",
    date: "2025-10-01",
    market: "ev-traction",
    maturity: "production-vehicle",
    qualifier: "reported",
    denominator: "named passenger-vehicle programmes",
    conflict:
      "Corrects framing that EESM is absent from production, but does not assert a shared brush implementation across all named vehicles.",
    caveat: "The retained sources do not prove BMW Gen5 or Nissan Ariya rotor excitation uses brushes; label those as production EESM only.",
    needsVerification: false,
  },
  {
    id: "contactless-wound-field-status",
    statement:
      "ZF I2SM and Valeo/MAHLE iBEE are contactless/brushless EESM development paths; their status must remain distinct from production EESM vehicle examples.",
    sourceIds: ["zf-i2sm", "valeo-ibee"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "eesm.contactless_zf",
    date: "2024-10-14",
    market: "ev-traction",
    maturity: "announced-development",
    qualifier: "prototype",
    denominator: "named contactless excitation programmes",
    needsVerification: false,
  },
  {
    id: "vimag-volektra-same-company",
    statement:
      "Public material and patent provenance connect Vimag's VMSM messaging with Volektra's rotating-transformer patent, but do not establish that they are one legal company or brand.",
    sourceIds: ["vimag-technology", "volektra-patent"],
    sourceType: "primary",
    evidenceStatus: "qualified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "vimag.volektra_corporate_relationship",
    date: "2026-07-01",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "company identity and brand relationship",
    conflict:
      "Corrects the original report's competing-box framing while avoiding an unsupported legal-entity assertion.",
    needsVerification: false,
  },
  {
    id: "virtual-magnet-is-contactless-wound-field",
    statement:
      "The VMSM/VMM mechanism is a brushless rotating-transformer-excited synchronous machine with DC rotor field windings, not a separate motor-physics family from contactless EESM.",
    sourceIds: ["volektra-patent"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "vimag.volektra_architecture",
    date: "2024-05-30",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "Vimag rotating-transformer patent framing",
    conflict:
      "Corrects the report's separate software-defined category by placing it under wound-field excitation.",
    needsVerification: false,
  },
  {
    id: "synrm-principle",
    statement:
      "A pure synchronous reluctance rotor is shaped steel with air barriers: it turns because the rotor's easy magnetic axis continuously aligns with the rotating stator field.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "industrial-drive",
    qualifier: "simulated",
    denominator: "representative pure synchronous-reluctance rotor",
    needsVerification: false,
  },
  {
    id: "synrm-inverter-power-factor",
    statement:
      "A pure SynRM's lower power factor can require more inverter kVA and cooling for the same wheel kW, which can offset a simple motor-BOM saving.",
    sourceIds: [dueDiligence],
    sourceType: "due-diligence",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "pure SynRM traction-drive comparison",
    caveat: "The magnitude is design-specific; show the relationship rather than an unsupported universal cost figure.",
    needsVerification: true,
  },
  {
    id: "pm-assisted-synrm-stack",
    statement:
      "Adding magnets into SynRM flux barriers creates PM-assisted SynRM, a stackable design that improves the same limitations and includes Tesla-style IPM-SynRM designs.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "PM-assisted synchronous-reluctance configuration",
    needsVerification: false,
  },
  {
    id: "industrial-induction-incumbent",
    statement:
      "Industrial motor substitution and EV traction substitution have different incumbents and motivations: ABB positions magnet-free SynRM as an efficient induction-motor retrofit, while EV traction examples focus on supply risk, packaging and drive-cycle performance.",
    sourceIds: ["abb-ie5-synrm"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "market.ev_vs_industrial",
    date: "2026-01-01",
    market: "industrial-drive",
    qualifier: "reported",
    denominator: "industrial motor market framing",
    conflict:
      "Corrects mixing industrial induction replacement with EV rare-earth substitution.",
    needsVerification: false,
  },
  {
    id: "ferrite-is-chemistry",
    statement:
      "Ferrite is a permanent-magnet chemistry that can be placed inside a PMSM; it is not a separate motor torque principle or a synonym for axial flux.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "motor-taxonomy teaching model",
    conflict:
      "Corrects a category that combines magnet chemistry and motor geometry as though they are one architecture.",
    needsVerification: false,
  },
  {
    id: "ferrite-remanence-energy-product",
    statement:
      "Remanence, coercivity and maximum energy product are separate magnetic properties; typical ferrite values sit well below NdFeB in remanence and energy product, forcing a geometry/package trade-off.",
    sourceIds: ["doe-magnet-roadmap"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show",
    evidenceRecordId: "ferrite.property_distinction",
    date: "2004-04-01",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "generic ferrite-to-NdFeB comparison; grades not specified",
    caveat: "Use grade-specific or explicitly illustrative property values. Do not label an energy-product gap as a coercivity ratio or 'field strength'.",
    conflict:
      "Corrects the original report's coercivity wording: the one-third figure belongs to remanence in the due-diligence explanation.",
    needsVerification: false,
  },
  {
    id: "ferrite-cold-constraint",
    statement:
      "For anisotropic ferrite with insufficient permeance coefficient, low-temperature operation can create irreversible demagnetisation risk after return to normal temperature.",
    sourceIds: ["tokyo-ferrite-cold-demag"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "ferrite.cold_demag",
    date: "n.d.",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "ferrite traction-motor cold operating condition",
    caveat: "Show the grade/circuit condition; do not imply every ferrite traction motor will fail in the cold.",
    needsVerification: false,
  },
  {
    id: "axial-flux-is-geometry",
    statement:
      "Axial flux describes the direction of magnetic flux and packaging geometry; it can be paired with ferrite, NdFeB or other magnet choices rather than standing for a material.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "motor geometry taxonomy",
    needsVerification: false,
  },
  {
    id: "proterial-power-speed-pair",
    statement:
      "Proterial's actual ferrite traction-motor test reported 102 kW at 15,000 rpm against a 110 kW, 10,000 rpm NdFeB comparison; power cannot be shown alone as parity.",
    sourceIds: ["proterial-ferrite-test"],
    sourceType: "company-claim",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "ferrite.proterial_motor_comparison",
    date: "2023-07-24",
    market: "ev-traction",
    maturity: "prototype",
    qualifier: "prototype",
    denominator: "specified Proterial prototype versus stated NdFeB baseline",
    quantitative: {
      label: "ferrite prototype power",
      value: 102,
      unit: "kW",
      denominator: "ferrite prototype at 15,000 rpm in the supplied due diligence",
    },
    caveat: "Show actual/simulated label, speed and comparator condition together.",
    needsVerification: false,
  },
  {
    id: "iron-nitride-is-chemistry",
    statement:
      "Iron nitride is a proposed permanent-magnet chemistry for a PMSM or variable-flux design; it does not by itself define the motor architecture.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "materials-scale-up",
    qualifier: "simulated",
    denominator: "motor taxonomy teaching model",
    needsVerification: false,
  },
  {
    id: "iron-nitride-saturation-not-hardness",
    statement:
      "Iron nitride's theoretical saturation-magnetisation narrative does not establish a drop-in traction magnet: coercivity, energy product and thermal stability remain separate design gates.",
    sourceIds: ["niron-variable-flux-patent"],
    sourceType: "primary",
    evidenceStatus: "qualified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "iron_nitride.actual_vs_theory",
    date: "2025-08-28",
    market: "materials-scale-up",
    qualifier: "reported",
    denominator: "iron-nitride permanent-magnet comparison",
    conflict:
      "Corrects the report's inference from 2.5 T saturation to a 'vastly stronger' drop-in traction magnet.",
    needsVerification: false,
  },
  {
    id: "niron-material-range",
    statement:
      "Niron's published variable-flux patent specifies iron-nitride magnets with a 2,000–4,000 Oe coercivity range; that material property is not a full vehicle-motor performance comparison.",
    sourceIds: ["niron-variable-flux-patent"],
    sourceType: "primary",
    evidenceStatus: "qualified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "iron_nitride.actual_vs_theory",
    date: "2025-08-28",
    market: "materials-scale-up",
    maturity: "materials-scale-up",
    qualifier: "reported",
    denominator: "iron-nitride magnet property specified in a published variable-flux patent",
    quantitative: {
      label: "specified coercivity range",
      value: [2000, 4000],
      unit: "Oe",
      denominator: "iron-nitride magnets specified in Niron's published variable-flux patent",
    },
    caveat: "Material-level patent figures do not establish drop-in vehicle traction performance.",
    needsVerification: false,
  },
  {
    id: "iron-nitride-thermal-margin",
    statement:
      "Peer-reviewed Fe16N2 literature reports decomposition around 500 K in the cited material system; thermal stability remains an active materials-development gate rather than one universal vehicle limit.",
    sourceIds: ["fe16n2-thermal-paper"],
    sourceType: "primary",
    evidenceStatus: "qualified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "iron_nitride.thermal_constraint",
    date: "2021-03-15",
    market: "materials-scale-up",
    qualifier: "reported",
    denominator: "cited alpha-double-prime Fe16N2 material system",
    quantitative: {
      label: "reported decomposition point",
      value: 500,
      unit: "K",
      denominator: "cited alpha-double-prime Fe16N2 material system in peer-reviewed literature",
    },
    caveat: "Composition and processing matter; do not turn this source-specific result into a deterministic vehicle-temperature limit.",
    needsVerification: false,
  },
  {
    id: "matter-variable-flux-fit",
    statement:
      "Niron and Matter unveiled a Variable Flux Motor prototype at CES 2026 and said they will explore integration into Matter electric-motorcycle products.",
    sourceIds: ["matter-niron-vfm"],
    sourceType: "company-claim",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "iron_nitride.matter_vfm",
    date: "2026-01-07",
    market: "light-mobility",
    maturity: "prototype",
    qualifier: "prototype",
    denominator: "Matter variable-flux motor prototype framing",
    caveat: "Show CES prototype / exploratory integration, not a commercial vehicle launch.",
    needsVerification: false,
  },
  {
    id: "aem-srm-principle",
    statement:
      "A switched-reluctance motor sequences stator poles around a toothed steel rotor; Advanced Electric Machines pairs this reluctance approach with compressed aluminium stator windings.",
    sourceIds: ["aem-ssrd-datasheet"],
    sourceType: "company-claim",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "aem.ssrd_peak_continuous",
    date: "2025-11-01",
    market: "ev-traction",
    maturity: "announced-development",
    qualifier: "reported",
    denominator: "AEM SSRD architecture described in supplied due diligence",
    needsVerification: false,
  },
  {
    id: "aem-peak-continuous-gap",
    statement:
      "AEM's in-development SSRD CV3 prototype datasheet lists 308 kW peak at 8,000 rpm, 138 kW continuous and 30,000 rpm maximum speed; the visual must show peak and continuous together.",
    sourceIds: ["aem-ssrd-datasheet"],
    sourceType: "company-claim",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "aem.ssrd_peak_continuous",
    date: "2025-11-01",
    market: "ev-traction",
    maturity: "announced-development",
    qualifier: "peak",
    denominator: "AEM SSRD CV3 prototype datasheet",
    quantitative: {
      label: "peak power",
      value: 308,
      unit: "kW",
      denominator: "AEM SSRD CV3 prototype peak rating at 8,000 rpm",
    },
    caveat: "Display prototype / in-development status beside every figure.",
    conflict:
      "Corrects peak-only comparison against motors praised for continuous-to-peak performance.",
    needsVerification: false,
  },
  {
    id: "stackable-technologies",
    statement:
      "Motor choices stack: Conifer can be ferrite plus axial flux; PM-assisted SynRM is reluctance plus magnets; and Tesla's IPM-SynRM is an interior-magnet plus reluctance configuration.",
    sourceIds: [dueDiligence],
    sourceType: "teaching-model",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "simulated",
    denominator: "taxonomy examples in the supplied due diligence",
    needsVerification: false,
  },
  {
    id: "named-company-corrections",
    statement:
      "Public company material places Naxatra in radial/axial-flux motor work, Gati in appliance/HVAC use, EKMO in industrial ferrite drives, Conifer in 0.5–7.5 kW ferrite axial applications, and MAHLE SCT as permanently excited rather than magnet-free.",
    sourceIds: ["naxatra-profile", "gati-products", "ekmo-products", "conifer-products", "mahle-sct"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    date: "2026-01-01",
    market: "industrial-drive",
    qualifier: "reported",
    denominator: "company/product classifications in the supplied due diligence",
    conflict:
      "Corrects parent, market and product-category assignments in the original report.",
    needsVerification: false,
  },
  {
    id: "ibee-target-status",
    statement:
      "Valeo and MAHLE announced iBEE in October 2024 as a joint brushless EESM development targeting 220–350 kW peak, with first prototype testing planned by the end of 2024.",
    sourceIds: ["valeo-ibee"],
    sourceType: "company-claim",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "eesm.contactless_ibee",
    date: "2024-10-14",
    market: "ev-traction",
    maturity: "announced-development",
    qualifier: "target",
    denominator: "iBEE announced peak target range",
    quantitative: {
      label: "target power range",
      value: [220, 350],
      unit: "kW",
      denominator: "iBEE announced peak target range; first prototype test planned by end-2024",
    },
    caveat: "A target is not a production performance claim. No qualifying source in the audit establishes 2028 series production.",
    needsVerification: false,
  },
  {
    id: "renault-efficiency-condition",
    statement:
      "Renault's 2026 release describes a third-generation no-rare-earth EESM with 93% motorway efficiency, 275 hp and 800 V architecture, planned from 2028.",
    sourceIds: ["renault-futureready"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "renault.e7a_efficiency",
    date: "2026-03-10",
    market: "ev-traction",
    maturity: "production-vehicle",
    qualifier: "reported",
    denominator: "Renault 2026 E7A motorway operating condition",
    quantitative: {
      label: "reported motorway efficiency",
      value: 93,
      unit: "%",
      denominator: "Renault 2026 E7A motorway operating condition",
    },
    caveat: "Do not relabel a condition-specific efficiency as a whole-system universal.",
    needsVerification: false,
  },
  {
    id: "vehicle-swap-burden",
    statement:
      "Changing a traction-motor architecture can affect motor, inverter/control, cooling and validation work; exact scope depends on the vehicle platform and architecture.",
    sourceIds: ["bmw-gen6-asm"],
    sourceType: "primary",
    evidenceStatus: "qualified",
    renderingPolicy: "show-with-condition",
    date: "2025-02-19",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "vehicle integration scope for a traction-motor architecture change",
    caveat: "Use a qualitative change map. Do not imply a universal component list or that all body/battery systems necessarily remain unchanged.",
    needsVerification: false,
  },
  {
    id: "vehicle-validation-window",
    statement:
      "No qualifying universal source supports a three-to-five-year validation and homologation duration for every motor swap.",
    sourceIds: ["bmw-gen6-asm"],
    sourceType: "primary",
    evidenceStatus: "unverified",
    renderingPolicy: "hide",
    evidenceRecordId: "vehicle.swap_burden",
    date: "2026-08-09",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "universal motor-swap validation duration; no qualifying denominator found",
    caveat: "Use qualitative validation workstreams. Reserve numeric programme durations for OEM-specific case studies.",
    needsVerification: true,
  },
  {
    id: "india-opportunity-capabilities",
    statement:
      "India's policy path can develop rare-earth-free motor technologies and components while separately building domestic rare-earth permanent-magnet capacity.",
    sourceIds: ["india-mhi-repm-policy"],
    sourceType: "primary",
    evidenceStatus: "verified",
    renderingPolicy: "show-with-condition",
    evidenceRecordId: "india.opportunity_policy",
    date: "2025-12-12",
    market: "ev-traction",
    qualifier: "reported",
    denominator: "India capability-stack framing in supplied due diligence",
    caveat: "Show complementary capability paths, not an unsupported market-share forecast or forced single choice.",
    needsVerification: false,
  },
] as const satisfies readonly RawClaim[];

/**
 * Qualify sourced editorial claims by default. Audit-backed records may opt
 * into a stronger `verified` status; unverified numbers are hidden by default.
 */
export const claims: readonly Claim[] = rawClaims.map((claim) => ({
  evidenceStatus: "qualified",
  renderingPolicy: "show-with-condition",
  ...claim,
}));

export type ClaimId = (typeof rawClaims)[number]["id"];
