import type { ContentPlacement, CoverageTopic } from "./schema.ts";

type RawCoverageTopic = Omit<CoverageTopic, "placement" | "reason">;

const coverage = (
  id: string,
  label: string,
  dueDiligencePoint: string,
  stepIds: readonly string[],
  claimIds: readonly string[],
  device: NonNullable<CoverageTopic["visual"]>["device"],
  visibleConsequence: string,
  interaction: string,
  fallback: string,
): RawCoverageTopic => ({
  id,
  label,
  dueDiligencePoint,
  stepIds,
  claimIds,
  visual: { device, visibleConsequence, interaction, fallback },
});

/**
 * This is the non-negotiable editorial coverage contract. Its granularity is
 * intentional: a future UI cannot report a due-diligence item as "covered"
 * merely because a paragraph mentions it. Every item has a named visual,
 * reader action and non-motion fallback.
 */
const rawCoverageMatrix = [
  coverage(
    "dd-01-market-is-early",
    "Rare-earth-free market share is small and leaves an opening",
    "1",
    ["market-early-share", "india-capability-stack"],
    ["market-rare-earth-free-share-small", "india-opportunity-capabilities"],
    "before-after-comparison",
    "A 100-motor field highlights the reported rare-earth-free share and a capability stack lights by architecture.",
    "Drag market share and select an architecture.",
    "Static 100-token grid and capability stack.",
  ),
  coverage(
    "dd-02-car-to-stator",
    "Car placement, drive unit, stator, rotor and three-phase PMSM mechanism",
    "2",
    ["car-transparent-cutaway", "power-path-flow", "drive-unit-extract", "pmsm-assemble-stator", "pmsm-three-phase-field", "pmsm-rotor-lock"],
    ["pmsm-stator-three-phase-field", "pmsm-synchronous-torque-angle"],
    "exploded-model",
    "The car opens to a drive unit, then the motor assembles into stator, air gap and rotor while timed currents rotate a field.",
    "Toggle axle layout, scrub energy path, assemble layers and vary load/frequency.",
    "Static car cutaway, component route and motor assembly storyboard.",
  ),
  coverage(
    "dd-02-ipm-retention-reluctance",
    "IPM magnet retention, hard magnet paths and reluctance torque",
    "2",
    ["ipm-rotor-cutaway", "ipm-reluctance-overlay"],
    ["ipm-magnets-buried", "ipm-reluctance-torque"],
    "microscopic-cutaway",
    "The IPM rotor exposes steel bridges, buried magnets, flux paths and separate magnet/reluctance torque arrows.",
    "Toggle high speed and flux paths; blend magnet and reluctance contributions.",
    "Annotated IPM cross-section and two-torque split view.",
  ),
  coverage(
    "dd-03-remanence-and-coercivity",
    "Remanence, coercivity and NdFeB division of labour",
    "3",
    ["remanence-strength", "coercivity-lock"],
    ["magnet-remanence-definition", "magnet-coercivity-definition", "ndfeb-division-of-labour"],
    "force-vector-overlay",
    "Field lines persist after assistance is removed; an opposing field reverses a lower-coercivity example first.",
    "Remove helper field and drag opposing field.",
    "Before/after magnet field and reversal-threshold diagrams.",
  ),
  coverage(
    "dd-03-hot-demagnetisation",
    "Heat plus opposing stator field can permanently demagnetise a traction magnet",
    "3",
    ["heat-demagnetisation"],
    ["traction-temperature-range", "coercivity-temperature-sensitivity"],
    "thermal-map",
    "Temperature and opposing field erode a visible coercivity margin; a reversed region remains after cooling.",
    "Raise temperature and acceleration field, then cool.",
    "Temperature-to-margin plot plus before/after domain state.",
  ),
  coverage(
    "dd-03-dy-tb-tradeoff",
    "Dy/Tb preserve high-temperature coercivity but trade against strength",
    "3",
    ["dy-tb-tradeoff"],
    ["dy-tb-thermal-role", "dy-strength-tradeoff", "illustrative-magnet-composition"],
    "parameter-slider",
    "A protective HREE layer increases reversal margin while a separate field-strength indicator changes.",
    "Move the Dy/Tb-content slider.",
    "Static two-composition trade-off comparison.",
  ),
  coverage(
    "dd-03-grain-boundary-diffusion",
    "Grain-boundary diffusion protects likely reversal sites with less HREE",
    "3",
    ["grain-boundary-diffusion"],
    ["gbd-grain-shell"],
    "microscopic-cutaway",
    "A reversal seed begins at the grain edge; the protective shell moves from uniform bulk doping to a boundary layer.",
    "Toggle uniform doping versus grain-boundary diffusion and play nucleation.",
    "Side-by-side grain cross-sections with an edge seed marker.",
  ),
  coverage(
    "dd-03-smco-and-cooling",
    "Cooling and SmCo as thermal design routes",
    "3",
    ["cooling-and-smco"],
    ["rotor-oil-cooling-reduces-hree", "smco-temperature-position"],
    "thermal-map",
    "Rotor oil cooling lowers the displayed magnet temperature; a separate material tile positions SmCo without calling it free.",
    "Toggle rotor cooling and material comparison.",
    "Cool/hot rotor cutaway and static material position card.",
  ),
  coverage(
    "dd-04-light-versus-heavy-ree",
    "HREE export-control exposure differs from Nd/Pr exposure",
    "4",
    ["light-and-heavy-ree-supply"],
    ["hree-controls-distinct-from-ndpr"],
    "matrix",
    "Nd/Pr and Dy/Tb split into distinct magnet-role and mitigation columns.",
    "Select a material group.",
    "Two-column supply/role map.",
  ),
  coverage(
    "dd-04-lowest-change-route",
    "Cooling and GBD as cheaper/faster HREE-reduction route",
    "4",
    ["mitigation-ladder", "vehicle-survivors-and-changes"],
    ["reduced-hree-near-drop-in", "proterial-hree-free-ndfeb", "rotor-oil-cooling-reduces-hree"],
    "timeline",
    "A five-rung ladder shows which vehicle systems change as the response grows from cooling to new architecture.",
    "Select an intervention rung.",
    "Static intervention ladder with change footprints.",
  ),
  coverage(
    "dd-05-back-emf",
    "Permanent magnets create high-speed back-EMF",
    "5",
    ["back-emf-speed-sweep"],
    ["back-emf-constraint"],
    "parameter-slider",
    "Back-EMF rises toward a fixed DC-bus limit as speed increases.",
    "Move the motor-speed slider.",
    "Voltage-versus-speed curve with DC-bus ceiling.",
  ),
  coverage(
    "dd-05-field-weakening",
    "Field weakening consumes current to oppose permanent flux",
    "5",
    ["field-weakening-current"],
    ["field-weakening-no-torque"],
    "force-vector-overlay",
    "A cancelling current vector appears opposite magnet flux when speed exceeds the base-speed region.",
    "Drag the high-speed control past the voltage limit.",
    "Current-vector triangle with cancelling component.",
  ),
  coverage(
    "dd-05-pmsm-fault",
    "PMSM inverter-failure-at-speed difference",
    "5",
    ["inverter-fault-at-speed"],
    ["pmsm-inverter-failure-risk"],
    "before-after-comparison",
    "PMSM field persists after a fault while commanded wound-field excitation fades.",
    "Toggle inverter fault and reset.",
    "Static PMSM versus wound-field fault panels.",
  ),
  coverage(
    "dd-06-motor-families",
    "Synchronous versus asynchronous motor families",
    "6",
    ["sync-async-family-tree"],
    ["motor-family-sync-async"],
    "matrix",
    "Family tiles separate field source and synchronous speed relationship from induction slip.",
    "Select a family tile.",
    "Two-branch family tree.",
  ),
  coverage(
    "dd-07-induction-mechanism",
    "Induction squirrel cage, Faraday current, torque and slip",
    "7",
    ["induction-cage-lab", "induction-slip-heat-coast"],
    ["induction-squirrel-cage", "induction-slip-range"],
    "animated-field",
    "A moving stator field induces cage current and torque; load visibly widens the rotor-field speed gap.",
    "Play the field, vary relative speed and increase load.",
    "Three-frame squirrel-cage mechanism plus load-state triptych.",
  ),
  coverage(
    "dd-07-induction-ev-tradeoff",
    "Induction efficiency, rotor heat, coasting and mixed-axle use",
    "7",
    ["induction-slip-heat-coast", "induction-mixed-axle", "mixed-axle-revisit"],
    ["induction-rotor-loss-and-coast", "induction-ev-efficiency-tradeoff", "induction-mixed-axle-use"],
    "vehicle-impact-map",
    "Rotor heat grows under load, then rotor field vanishes on coast; a dual-axle car changes active motor by mode.",
    "Increase load, cut power and select drive mode.",
    "Static heat/coast triptych and PM/induction axle map.",
  ),
  coverage(
    "dd-08-wound-field-principle",
    "Wound-field rotor, controllable flux and rotor cooling",
    "8",
    ["wound-field-lab"],
    ["wound-field-principle", "wound-field-advantages-costs"],
    "rotor-morph",
    "Permanent magnets morph into rotor windings while excitation and hollow-shaft oil cooling visibly change the rotor state.",
    "Morph rotor, adjust excitation and toggle cooling.",
    "PMSM/EESM rotor comparison with cooling path.",
  ),
  coverage(
    "dd-08-brushes-versus-contactless",
    "Production EESM versus emerging contactless excitation",
    "8",
    ["brushed-contactless-status", "evidence-maturity-lanes"],
    ["wound-field-production-brushes", "contactless-wound-field-status"],
    "evidence-lane",
    "Production EESM and rotating-transformer EESM are placed on separate production and development evidence lanes.",
    "Toggle production/contactless mode and open the evidence card.",
    "Static two-lane status diagram with a transfer-hardware scope note.",
  ),
  coverage(
    "dd-08-vimag-volektra-correction",
    "Vimag/Volektra relationship and virtual-magnet correction",
    "8",
    ["brushed-contactless-status", "stackable-motor-builder", "evidence-maturity-lanes"],
    ["vimag-volektra-same-company", "virtual-magnet-is-contactless-wound-field"],
    "evidence-lane",
    "One company/brand relationship token is connected to a rotating-transformer wound-field cross-section.",
    "Open the company token and load the contactless wound-field configuration.",
    "Static company-relationship/evidence lane and configuration card.",
  ),
  coverage(
    "dd-09-synrm-mechanism",
    "Pure SynRM shaped steel, flux barriers and power-factor trade-off",
    "9",
    ["pure-synrm-lab"],
    ["synrm-principle", "synrm-inverter-power-factor"],
    "force-vector-overlay",
    "Flux barriers form an easy axis while a kVA overlay rises for the same wheel-kW marker.",
    "Play the field and adjust power factor.",
    "Barrier-rotor cross-section plus static kW/kVA comparison.",
  ),
  coverage(
    "dd-09-pm-assisted-synrm",
    "PM-assisted SynRM and Tesla as a stacked design",
    "9",
    ["pm-assisted-synrm-lab", "stackable-motor-builder"],
    ["pm-assisted-synrm-stack", "stackable-technologies", "ipm-reluctance-torque"],
    "rotor-morph",
    "Magnets fade into the same reluctance barriers, revealing a torque mix rather than an exclusive architecture swap.",
    "Move the magnet-assist slider and load Tesla IPM-SynRM.",
    "Same rotor before/after magnet assist.",
  ),
  coverage(
    "dd-09-industrial-synrm-context",
    "Industrial SynRM innovation context and induction incumbent",
    "9",
    ["two-markets-switch", "evidence-maturity-lanes"],
    ["industrial-induction-incumbent"],
    "matrix",
    "Industrial lane changes incumbent to induction and reason-to-change to efficiency; ABB sits in that lane.",
    "Toggle the market lane and open the ABB record.",
    "Static EV-versus-industrial comparison.",
  ),
  coverage(
    "dd-10-ferrite-physics",
    "Ferrite remanence/energy product, cold constraint and compensation",
    "10",
    ["ferrite-material-not-architecture"],
    ["ferrite-is-chemistry", "ferrite-remanence-energy-product", "ferrite-cold-constraint"],
    "before-after-comparison",
    "Same PM architecture swaps NdFeB for ferrite while flux, size/speed compensation and a cold-condition warning change.",
    "Swap chemistry and select compensation path.",
    "Static magnet-swap and compensation map.",
  ),
  coverage(
    "dd-10-ferrite-axial-flux",
    "Axial flux is geometry; ferrite can stack with it",
    "10",
    ["axial-flux-geometry", "stackable-motor-builder"],
    ["axial-flux-is-geometry", "stackable-technologies"],
    "rotor-morph",
    "A radial motor becomes axial while ferrite/NdFeB material remains independently selectable.",
    "Toggle geometry and chemistry separately.",
    "Radial/axial cross-sections with separate chemistry layer.",
  ),
  coverage(
    "dd-10-proterial-condition",
    "Proterial power must be shown with speed",
    "10",
    ["proterial-power-speed", "claim-condition-checker"],
    ["proterial-power-speed-pair"],
    "matrix",
    "Power bars lock to their rpm values so the comparison cannot remain power-only.",
    "Toggle operating-condition labels and add them to the claim card.",
    "Aligned power/rpm comparison.",
  ),
  coverage(
    "dd-10-iron-nitride-physics",
    "Iron nitride saturation versus remanence, coercivity, energy product and heat",
    "10",
    ["iron-nitride-property-board"],
    ["iron-nitride-is-chemistry", "iron-nitride-saturation-not-hardness", "niron-material-range", "iron-nitride-thermal-margin"],
    "matrix",
    "Five separate material properties prevent a saturation-only 'strongest magnet' conclusion.",
    "Select a property and trigger the drop-in checklist.",
    "Static five-property material ledger.",
  ),
  coverage(
    "dd-10-matter-variable-flux",
    "Matter variable-flux prototype and useful low coercivity",
    "10",
    ["matter-variable-flux", "evidence-maturity-lanes"],
    ["matter-variable-flux-fit"],
    "parameter-slider",
    "Variable-flux control shifts the magnet state between low-speed and high-speed modes while prototype status remains visible.",
    "Adjust speed and toggle variable-flux control.",
    "Static low-speed/high-speed flux comparison.",
  ),
  coverage(
    "dd-11-aem-srm-aluminium",
    "AEM switched reluctance, aluminium windings, high speed and peak/continuous gap",
    "11",
    ["srm-aem-lab", "claim-condition-checker"],
    ["aem-srm-principle", "aem-peak-continuous-gap"],
    "animated-field",
    "Stator poles sequence around a toothed rotor while time at demand reveals peak versus continuous power and a material toggle changes windings.",
    "Play pole sequence, hold demand and toggle winding material.",
    "Static sequence, aluminium cross-section and duty bar.",
  ),
  coverage(
    "dd-12-stack-not-boxes",
    "Technologies stack instead of competing in exclusive boxes",
    "12",
    ["stackable-motor-builder", "pm-assisted-synrm-lab", "axial-flux-geometry"],
    ["stackable-technologies"],
    "configuration-builder",
    "Independent configuration layers reproduce Conifer ferrite/axial, Tesla IPM-SynRM and AEM SRM/aluminium combinations.",
    "Select independent layers or load a named example.",
    "Static five-axis configuration builder.",
  ),
  coverage(
    "dd-13-company-parent-market-corrections",
    "Naxatra, Gati, EKMO, Conifer and Mahle SCT corrections",
    "13",
    ["two-markets-switch", "evidence-maturity-lanes", "claim-condition-checker"],
    ["named-company-corrections"],
    "evidence-lane",
    "Company tokens stay in their corrected market/maturity lane and surface a correction note when opened.",
    "Filter market and open company tokens.",
    "Static evidence board with correction-note markers.",
  ),
  coverage(
    "dd-14-vehicle-change-map",
    "What must change in car and drive unit for each alternative",
    "14",
    ["vehicle-survivors-and-changes", "inverter-and-cooling-burden", "swap-burden-spectrum"],
    ["vehicle-swap-burden", "reduced-hree-near-drop-in", "wound-field-advantages-costs", "synrm-inverter-power-factor"],
    "vehicle-impact-map",
    "Architecture selection recolours retained car systems and redesigned inverter, cooling, package and control systems.",
    "Select architecture, inspect changed modules and sort burden matrix.",
    "Static car impact maps and a six-route change matrix.",
  ),
  coverage(
    "dd-14-validation-time",
    "Three-to-five-year validation and homologation runway",
    "14",
    ["validation-runway"],
    ["vehicle-validation-window"],
    "timeline",
    "Route selection lights package, controls, cooling, NVH, safety and homologation workstreams across an illustrative window.",
    "Select route and scrub programme time.",
    "Static multi-lane validation timeline.",
  ),
  coverage(
    "dd-15-market-separation",
    "EV traction rare-earth issue versus industrial efficiency market",
    "15",
    ["two-markets-switch"],
    ["industrial-induction-incumbent", "market-rare-earth-free-share-small"],
    "matrix",
    "The same architecture appears under a different incumbent and reason-to-change when market lane changes.",
    "Toggle market lanes.",
    "Static EV-versus-industrial market matrix.",
  ),
  coverage(
    "dd-16-quantitative-context",
    "iBEE target date, Renault condition and named factual corrections",
    "16",
    ["evidence-maturity-lanes", "claim-condition-checker"],
    ["ibee-target-status", "renault-efficiency-condition", "named-company-corrections"],
    "before-after-comparison",
    "Condition layers reveal target date, operating condition, market, maturity and source before a claim can be shown as complete.",
    "Toggle evidence fields on a claim card and inspect evidence tokens.",
    "Static incomplete/complete provenance card.",
  ),
] as const satisfies readonly RawCoverageTopic[];

const coverageClassification: Record<
  string,
  { placement: Exclude<ContentPlacement, "omit">; reason: string }
> = {
  "dd-01-market-is-early": { placement: "optional-deep-dive", reason: "Useful market context, but the default route must not begin with an unsupported share estimate." },
  "dd-02-car-to-stator": { placement: "main", reason: "Core spatial and mechanical foundation for beginners." },
  "dd-02-ipm-retention-reluctance": { placement: "main", reason: "Explains the mainstream IPM-SynRM mechanism before alternatives." },
  "dd-03-remanence-and-coercivity": { placement: "main", reason: "Essential vocabulary for every later material comparison." },
  "dd-03-hot-demagnetisation": { placement: "main", reason: "Shows the physical reason heat and coercivity matter." },
  "dd-03-dy-tb-tradeoff": { placement: "main", reason: "Essential supply/material mechanism." },
  "dd-03-grain-boundary-diffusion": { placement: "optional-deep-dive", reason: "A valuable microscopic mechanism after the first-pass Dy/Tb trade-off is clear." },
  "dd-03-smco-and-cooling": { placement: "optional-deep-dive", reason: "Useful thermal routes after the core Dy/Tb mechanism is understood." },
  "dd-04-light-versus-heavy-ree": { placement: "main", reason: "Prevents treating all rare-earth exposure as one problem." },
  "dd-04-lowest-change-route": { placement: "main", reason: "Connects materials intervention to the decision map." },
  "dd-05-back-emf": { placement: "main", reason: "Essential PMSM engineering limitation." },
  "dd-05-field-weakening": { placement: "main", reason: "Visible cause/effect explanation of the high-speed trade-off." },
  "dd-05-pmsm-fault": { placement: "optional-deep-dive", reason: "Safety nuance is useful after the core high-speed field-weakening explanation." },
  "dd-06-motor-families": { placement: "main", reason: "Gives a simple mental map before alternative labs." },
  "dd-07-induction-mechanism": { placement: "main", reason: "One of the core alternative torque mechanisms." },
  "dd-07-induction-ev-tradeoff": { placement: "optional-deep-dive", reason: "Mixed-axle deployment adds context after the induction mechanism is learned." },
  "dd-08-wound-field-principle": { placement: "main", reason: "One of the core alternative torque mechanisms." },
  "dd-08-brushes-versus-contactless": { placement: "optional-deep-dive", reason: "Maturity/hardware nuance should not interrupt first-pass physics." },
  "dd-08-vimag-volektra-correction": { placement: "evidence-only", reason: "Corporate/provenance nuance belongs in the evidence drawer, not the first-pass lesson." },
  "dd-09-synrm-mechanism": { placement: "main", reason: "One of the core alternative torque mechanisms." },
  "dd-09-pm-assisted-synrm": { placement: "optional-deep-dive", reason: "The beginner route already meets reluctance torque in the IPM chapter." },
  "dd-09-industrial-synrm-context": { placement: "evidence-only", reason: "Industry lineage supports correct scope but is not necessary to understand the mechanism." },
  "dd-10-ferrite-physics": { placement: "main", reason: "Core material-substitution trade-off." },
  "dd-10-ferrite-axial-flux": { placement: "main", reason: "Essential taxonomy distinction." },
  "dd-10-proterial-condition": { placement: "evidence-only", reason: "Exact prototype comparison is an evidence-reading exercise after the core ferrite model." },
  "dd-10-iron-nitride-physics": { placement: "main", reason: "Corrects the most consequential material-science overclaim." },
  "dd-10-matter-variable-flux": { placement: "optional-deep-dive", reason: "Useful prototype application after the property board." },
  "dd-11-aem-srm-aluminium": { placement: "optional-deep-dive", reason: "AEM is a valuable specialised lab, not a prerequisite for first-pass comprehension." },
  "dd-12-stack-not-boxes": { placement: "main", reason: "The configuration builder resolves category errors across the entire report." },
  "dd-13-company-parent-market-corrections": { placement: "evidence-only", reason: "Company placement corrections remain searchable evidence, not a novice mechanism lesson." },
  "dd-14-vehicle-change-map": { placement: "main", reason: "Essential decision consequence after alternatives are understood." },
  "dd-14-validation-time": { placement: "optional-deep-dive", reason: "Programme nuance belongs after the physical swap burden is clear." },
  "dd-15-market-separation": { placement: "main", reason: "Essential safeguard against mixing EV traction with industrial/appliance claims." },
  "dd-16-quantitative-context": { placement: "evidence-only", reason: "Provenance-reading is available on demand rather than interrupting the main learning flow." },
};

const omittedCoverage: CoverageTopic = {
  id: "dd-16-incidental-company-financing",
  label: "Incidental funding, city and round-size corrections",
  dueDiligencePoint: "16",
  placement: "omit",
  stepIds: [],
  claimIds: [],
  reason: "Funding amounts and incidental company-location corrections do not change a beginner's understanding of PMSM mechanisms or the alternative decision map; retain them in the research audit, not the learning route.",
};

export const coverageMatrix: readonly CoverageTopic[] = [
  ...rawCoverageMatrix.map((topic) => {
    const classification = coverageClassification[topic.id];
    if (!classification) throw new Error(`Missing coverage classification: ${topic.id}`);
    return { ...topic, ...classification };
  }),
  omittedCoverage,
];

/**
 * Fixed editorial checklist, intentionally not derived from the matrix. If a
 * future edit removes a row, validation catches the loss instead of quietly
 * redefining "complete" around whatever remains.
 */
export const requiredCoverageTopicIds = [
  "dd-01-market-is-early",
  "dd-02-car-to-stator",
  "dd-02-ipm-retention-reluctance",
  "dd-03-remanence-and-coercivity",
  "dd-03-hot-demagnetisation",
  "dd-03-dy-tb-tradeoff",
  "dd-03-grain-boundary-diffusion",
  "dd-03-smco-and-cooling",
  "dd-04-light-versus-heavy-ree",
  "dd-04-lowest-change-route",
  "dd-05-back-emf",
  "dd-05-field-weakening",
  "dd-05-pmsm-fault",
  "dd-06-motor-families",
  "dd-07-induction-mechanism",
  "dd-07-induction-ev-tradeoff",
  "dd-08-wound-field-principle",
  "dd-08-brushes-versus-contactless",
  "dd-08-vimag-volektra-correction",
  "dd-09-synrm-mechanism",
  "dd-09-pm-assisted-synrm",
  "dd-09-industrial-synrm-context",
  "dd-10-ferrite-physics",
  "dd-10-ferrite-axial-flux",
  "dd-10-proterial-condition",
  "dd-10-iron-nitride-physics",
  "dd-10-matter-variable-flux",
  "dd-11-aem-srm-aluminium",
  "dd-12-stack-not-boxes",
  "dd-13-company-parent-market-corrections",
  "dd-14-vehicle-change-map",
  "dd-14-validation-time",
  "dd-15-market-separation",
  "dd-16-quantitative-context",
  "dd-16-incidental-company-financing",
] as const;

/** @deprecated Use requiredCoverageTopicIds; this alias supports old imports. */
export const expectedCoverageTopicIds = requiredCoverageTopicIds;
