import type {
  CompanyExample,
  MotorConfiguration,
  PerformanceRecord,
} from "./schema.ts";

/**
 * Configurations are deliberately composable. Nothing in this list allows a
 * material (ferrite, iron nitride) or a geometry (axial flux) to masquerade as
 * an exclusive motor architecture.
 */
export const configurations = [
  {
    id: "ndfeb-ipm-synrm",
    label: "NdFeB IPM-SynRM",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "ndfeb",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["ipm-magnets-buried", "ipm-reluctance-torque", "back-emf-constraint"],
    notes: "Mainstream PMSM configuration in which reluctance torque contributes alongside magnet torque.",
  },
  {
    id: "reduced-hree-ipm",
    label: "Reduced-HREE NdFeB IPM",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "reduced-hree-ndfeb",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["gbd-grain-shell", "reduced-hree-near-drop-in", "rotor-oil-cooling-reduces-hree"],
    notes: "A material-and-thermal-management route that keeps the basic permanent-magnet machine architecture.",
  },
  {
    id: "hree-free-ndfeb-ipm",
    label: "HREE-free NdFeB IPM",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "hree-free-ndfeb",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["proterial-hree-free-ndfeb", "reduced-hree-near-drop-in"],
    notes: "A material route that removes Dy/Tb while retaining Nd/Pr and the permanent-magnet architecture.",
  },
  {
    id: "induction-cage-traction",
    label: "Squirrel-cage induction traction motor",
    torquePrinciple: "induction",
    excitation: "induced",
    magnetChemistry: "none",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["induction-squirrel-cage", "induction-slip-range", "induction-rotor-loss-and-coast"],
    notes: "The rotor field is induced on demand, so it disappears when the stator is de-energised.",
  },
  {
    id: "wound-field-production-traction",
    label: "Production electrically excited synchronous traction motor",
    torquePrinciple: "wound-field",
    excitation: "externally-excited",
    magnetChemistry: "none",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["wound-field-principle", "wound-field-advantages-costs", "wound-field-production-brushes"],
    notes: "A deployed EESM category. Its public evidence is intentionally separate from any unverified claim about the exact rotor-current transfer hardware of a named vehicle.",
  },
  {
    id: "wound-field-contactless-traction",
    label: "Contactless wound-field synchronous traction motor",
    torquePrinciple: "wound-field",
    excitation: "contactless",
    magnetChemistry: "none",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["contactless-wound-field-status", "virtual-magnet-is-contactless-wound-field"],
    notes: "A rotating-transformer excitation route that should be shown separately from production EESM examples whose public transfer hardware is not asserted.",
  },
  {
    id: "pure-synrm-industrial",
    label: "Pure synchronous reluctance motor",
    torquePrinciple: "synchronous-reluctance",
    excitation: "none",
    magnetChemistry: "none",
    geometry: "radial",
    windingMaterial: "copper",
    market: "industrial-drive",
    maturity: "industrial-product",
    claimIds: ["synrm-principle", "synrm-inverter-power-factor", "industrial-induction-incumbent"],
    notes: "A shaped-steel rotor without magnets or rotor windings; often sold as an efficient induction replacement in industry.",
  },
  {
    id: "pure-synrm-light-traction",
    label: "Pure synchronous reluctance light-traction motor",
    torquePrinciple: "synchronous-reluctance",
    excitation: "none",
    magnetChemistry: "none",
    geometry: "radial",
    windingMaterial: "copper",
    market: "light-mobility",
    maturity: "vehicle-pilot",
    claimIds: ["synrm-principle", "synrm-inverter-power-factor", "vehicle-swap-burden"],
    notes: "A light-traction application of the same reluctance principle; it remains separate from the industrial market story.",
  },
  {
    id: "pm-assisted-synrm",
    label: "PM-assisted SynRM",
    torquePrinciple: "synchronous-reluctance",
    excitation: "permanent",
    magnetChemistry: "ndfeb",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["pm-assisted-synrm-stack", "stackable-technologies"],
    notes: "Reluctance rotor barriers and permanent magnets coexist; it must not be presented as a mutually exclusive category.",
  },
  {
    id: "ferrite-axial-pm",
    label: "Ferrite axial-flux permanent-magnet motor",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "ferrite",
    geometry: "axial",
    windingMaterial: "copper",
    market: "industrial-drive",
    maturity: "industrial-product",
    claimIds: ["ferrite-is-chemistry", "ferrite-remanence-energy-product", "axial-flux-is-geometry", "stackable-technologies"],
    notes: "One possible stack: a weaker permanent-magnet chemistry paired with an axial-flux geometry.",
  },
  {
    id: "ferrite-radial-pm-prototype",
    label: "Ferrite radial-flux permanent-magnet prototype",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "ferrite",
    geometry: "radial",
    windingMaterial: "copper",
    market: "ev-traction",
    maturity: "prototype",
    claimIds: ["ferrite-is-chemistry", "ferrite-remanence-energy-product", "proterial-power-speed-pair"],
    notes: "A ferrite PMSM prototype whose geometry is kept separate from axial-flux claims.",
  },
  {
    id: "iron-nitride-pm-prototype",
    label: "Iron-nitride permanent-magnet prototype",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "iron-nitride",
    geometry: "radial",
    windingMaterial: "copper",
    market: "materials-scale-up",
    maturity: "prototype",
    claimIds: ["iron-nitride-is-chemistry", "iron-nitride-saturation-not-hardness", "niron-material-range"],
    notes: "A material route; production motor architecture and thermal qualification remain separate questions.",
  },
  {
    id: "iron-nitride-variable-flux",
    label: "Iron-nitride variable-flux motor prototype",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "iron-nitride",
    geometry: "radial",
    windingMaterial: "copper",
    market: "light-mobility",
    maturity: "prototype",
    claimIds: ["matter-variable-flux-fit", "iron-nitride-is-chemistry"],
    notes: "A prototype use case in which deliberately adjustable magnetisation is part of the motor concept.",
  },
  {
    id: "aem-aluminium-srm",
    label: "Aluminium-wound switched-reluctance drive",
    torquePrinciple: "switched-reluctance",
    excitation: "none",
    magnetChemistry: "none",
    geometry: "radial",
    windingMaterial: "aluminium",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["aem-srm-principle", "aem-peak-continuous-gap"],
    notes: "A reluctance architecture combined with aluminium stator windings, not a new magnet chemistry.",
  },
  {
    id: "gati-ferrite-appliance",
    label: "Ferrite appliance motor",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "ferrite",
    geometry: "radial",
    windingMaterial: "copper",
    market: "appliance",
    maturity: "industrial-product",
    claimIds: ["named-company-corrections", "industrial-induction-incumbent"],
    notes: "Kept in the appliance lane so a single-phase product is never depicted as EV traction.",
  },
  {
    id: "ekmo-line-start-ferrite",
    label: "Line-start ferrite industrial motor",
    torquePrinciple: "permanent-magnet",
    excitation: "permanent",
    magnetChemistry: "ferrite",
    geometry: "radial",
    windingMaterial: "copper",
    market: "industrial-drive",
    maturity: "industrial-product",
    claimIds: ["named-company-corrections", "industrial-induction-incumbent"],
    notes: "Fixed-speed, grid-connected industrial classification; not structurally a variable-speed traction motor.",
  },
] as const satisfies readonly MotorConfiguration[];

export const performance = [
  {
    id: "aem-ssrd-power",
    subject: "Advanced Electric Machines SSRD",
    market: "ev-traction",
    maturity: "announced-development",
    sourceIds: ["aem-ssrd-datasheet"],
    sourceType: "company-claim",
    date: "2025-11-01",
    qualifier: "peak",
    requiresContinuousPair: true,
    peak: {
      label: "peak power",
      value: 308,
      unit: "kW",
      denominator: "AEM SSRD CV3 prototype datasheet; peak rating at 8,000 rpm",
    },
    continuous: {
      label: "continuous power",
      value: 138,
      unit: "kW",
      denominator: "AEM SSRD CV3 prototype datasheet",
    },
    speed: {
      label: "maximum speed",
      value: 30000,
      unit: "rpm",
      denominator: "AEM SSRD CV3 prototype datasheet; maximum speed rather than peak-power speed",
    },
    caveat: "Prototype / in-development status, peak condition and continuous rating must travel together.",
    needsVerification: false,
  },
  {
    id: "proterial-ferrite-comparison",
    subject: "Proterial ferrite EV-motor prototype",
    market: "ev-traction",
    maturity: "prototype",
    sourceIds: ["proterial-ferrite-test"],
    sourceType: "company-claim",
    date: "2023-07-24",
    qualifier: "prototype",
    requiresContinuousPair: false,
    peak: {
      label: "reported prototype power",
      value: 102,
      unit: "kW",
      denominator: "Proterial actual ferrite-motor test",
    },
    speed: {
      label: "reported prototype speed",
      value: 15000,
      unit: "rpm",
      denominator: "same Proterial actual ferrite-motor test operating point",
    },
    caveat: "Pair with the 110 kW / 10,000 rpm NdFeB comparison and keep actual/simulated status visible; no continuous rating is supplied.",
    needsVerification: false,
  },
  {
    id: "ibee-target-range",
    subject: "Valeo/Mahle iBEE",
    market: "ev-traction",
    maturity: "announced-development",
    sourceIds: ["valeo-ibee"],
    sourceType: "company-claim",
    date: "2024-10-14",
    qualifier: "target",
    requiresContinuousPair: false,
    peak: {
      label: "target output range",
      value: [220, 350],
      unit: "kW",
      denominator: "iBEE announced target range; peak output",
    },
    caveat: "A target range is neither a production rating nor a continuous output rating. No qualifying audit source establishes 2028 series production.",
    needsVerification: false,
  },
] as const satisfies readonly PerformanceRecord[];

export const examples = [
  {
    id: "bmw-edrive",
    organisation: "BMW Group",
    product: "Fifth- and sixth-generation eDrive programmes",
    configurationId: "wound-field-production-traction",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["wound-field-production-brushes", "wound-field-advantages-costs"],
    correction: "Treat as a production EESM example, not evidence that contactless excitation is in production or that the named programme uses brushes.",
    needsVerification: false,
  },
  {
    id: "renault-wound-field",
    organisation: "Renault Group",
    product: "Zoe / E7A programme",
    configurationId: "wound-field-production-traction",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["wound-field-production-brushes", "renault-efficiency-condition"],
    correction: "Keep production motor history separate from future E7A programme and condition-specific efficiency claims.",
    needsVerification: false,
  },
  {
    id: "nissan-ariya",
    organisation: "Nissan",
    product: "Ariya",
    configurationId: "wound-field-production-traction",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["wound-field-production-brushes"],
    correction: "Use as a production EESM card. The audit does not establish its rotor-current transfer hardware.",
    needsVerification: false,
  },
  {
    id: "zf-i2sm",
    organisation: "ZF Friedrichshafen",
    product: "I2SM",
    configurationId: "wound-field-contactless-traction",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["contactless-wound-field-status"],
    correction: "Use an announced-development lane until a production vehicle is verified.",
    needsVerification: true,
  },
  {
    id: "mahle-mct",
    organisation: "Mahle",
    product: "MCT",
    configurationId: "wound-field-contactless-traction",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["contactless-wound-field-status"],
    correction: "Contactless excitation concept, distinct from Mahle SCT permanent-magnet cooling.",
    needsVerification: true,
  },
  {
    id: "valeo-ibee",
    organisation: "Valeo / Mahle",
    product: "iBEE",
    configurationId: "wound-field-contactless-traction",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["ibee-target-status", "contactless-wound-field-status"],
    performanceIds: ["ibee-target-range"],
    needsVerification: true,
  },
  {
    id: "mahle-sct",
    organisation: "Mahle",
    product: "SCT",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["named-company-corrections"],
    correction: "SCT is a permanent-magnet motor with oil cooling; it must not be placed in the magnet-free contactless lane.",
    needsVerification: true,
  },
  {
    id: "vimag-volektra",
    organisation: "Vimag / Volektra",
    product: "Rotating-transformer excited synchronous motor",
    configurationId: "wound-field-contactless-traction",
    market: "ev-traction",
    maturity: "vehicle-pilot",
    claimIds: ["vimag-volektra-same-company", "virtual-magnet-is-contactless-wound-field"],
    correction: "Represent as one company/brand relationship and one contactlessly excited wound-field family.",
    needsVerification: true,
  },
  {
    id: "tesla-ipm-synrm",
    organisation: "Tesla",
    product: "Model 3-era IPM-SynRM architecture",
    configurationId: "pm-assisted-synrm",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["ipm-reluctance-torque", "pm-assisted-synrm-stack", "stackable-technologies"],
    correction: "Use as an example that PM and reluctance effects already coexist; do not assert an unannounced rare-earth-free production motor.",
    needsVerification: true,
  },
  {
    id: "audi-induction-axle",
    organisation: "Audi",
    product: "Q6 e-tron front axle",
    configurationId: "induction-cage-traction",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["induction-mixed-axle-use", "induction-rotor-loss-and-coast"],
    correction: "Show as a mixed-axle strategy and verify exact model/axle implementation before release.",
    needsVerification: true,
  },
  {
    id: "bmw-induction-axle",
    organisation: "BMW Group",
    product: "Mixed-axle motor strategy referenced in due diligence",
    configurationId: "induction-cage-traction",
    market: "ev-traction",
    maturity: "production-vehicle",
    claimIds: ["induction-mixed-axle-use"],
    needsVerification: true,
  },
  {
    id: "abb-synrm",
    organisation: "ABB",
    product: "Industrial SynRM",
    configurationId: "pure-synrm-industrial",
    market: "industrial-drive",
    maturity: "industrial-product",
    claimIds: ["synrm-principle", "industrial-induction-incumbent"],
    correction: "Place in the industrial efficiency lane, not an India-only EV-traction innovation lane.",
    needsVerification: true,
  },
  {
    id: "chara-synrm",
    organisation: "Chara Technologies",
    product: "Reluctance traction drives",
    configurationId: "pure-synrm-light-traction",
    market: "light-mobility",
    maturity: "vehicle-pilot",
    claimIds: ["synrm-principle", "vehicle-swap-burden"],
    correction: "Keep its target use in light mobility distinct from a passenger-car universal claim.",
    needsVerification: true,
  },
  {
    id: "viridian-ingni",
    organisation: "Viridian Ingni Propulsion",
    product: "Reluctance / hybrid-ferrite motors",
    market: "light-mobility",
    maturity: "vehicle-pilot",
    claimIds: ["synrm-principle", "ferrite-is-chemistry"],
    correction: "Show the hybrid stack without recasting ferrite as a torque principle.",
    needsVerification: true,
  },
  {
    id: "conifer",
    organisation: "Conifer",
    product: "Ferrite axial-flux platform",
    configurationId: "ferrite-axial-pm",
    market: "industrial-drive",
    maturity: "industrial-product",
    claimIds: ["stackable-technologies", "named-company-corrections"],
    correction: "Keep its public 0.5–7.5 kW ferrite axial scope and industrial/light-mobility applications visible; do not present it as a disclosed full-size passenger-car programme.",
    needsVerification: false,
  },
  {
    id: "proterial",
    organisation: "Proterial",
    product: "Ferrite traction-motor prototype",
    configurationId: "ferrite-radial-pm-prototype",
    market: "ev-traction",
    maturity: "prototype",
    claimIds: ["proterial-power-speed-pair", "ferrite-remanence-energy-product"],
    performanceIds: ["proterial-ferrite-comparison"],
    needsVerification: true,
  },
  {
    id: "niron",
    organisation: "Niron Magnetics",
    product: "Iron-nitride magnet material",
    configurationId: "iron-nitride-pm-prototype",
    market: "materials-scale-up",
    maturity: "materials-scale-up",
    claimIds: ["niron-material-range", "iron-nitride-thermal-margin"],
    correction: "A material-scale-up record, not a fully qualified production traction motor.",
    needsVerification: true,
  },
  {
    id: "matter-vfm",
    organisation: "Matter",
    product: "Variable-flux motor prototype",
    configurationId: "iron-nitride-variable-flux",
    market: "light-mobility",
    maturity: "prototype",
    claimIds: ["matter-variable-flux-fit"],
    needsVerification: true,
  },
  {
    id: "aem-ssrd",
    organisation: "Advanced Electric Machines",
    product: "SSRD",
    configurationId: "aem-aluminium-srm",
    market: "ev-traction",
    maturity: "announced-development",
    claimIds: ["aem-srm-principle", "aem-peak-continuous-gap"],
    performanceIds: ["aem-ssrd-power"],
    needsVerification: true,
  },
  {
    id: "naxatra",
    organisation: "Naxatra Labs",
    product: "Axial and radial flux motor work",
    market: "light-mobility",
    maturity: "vehicle-pilot",
    claimIds: ["named-company-corrections", "axial-flux-is-geometry"],
    correction: "Do not place Naxatra under virtual magnet; the due diligence places it in axial and radial flux work.",
    needsVerification: true,
  },
  {
    id: "gati",
    organisation: "Gati Drives",
    product: "Single-phase appliance motors",
    configurationId: "gati-ferrite-appliance",
    market: "appliance",
    maturity: "industrial-product",
    claimIds: ["named-company-corrections"],
    correction: "Appliance market, not EV traction.",
    needsVerification: true,
  },
  {
    id: "ekmo",
    organisation: "EKMO",
    product: "Line-start industrial motor",
    configurationId: "ekmo-line-start-ferrite",
    market: "industrial-drive",
    maturity: "industrial-product",
    claimIds: ["named-company-corrections"],
    correction: "Fixed-speed grid-connected industrial product, not traction.",
    needsVerification: true,
  },
  {
    id: "matel",
    organisation: "Matel Motion and Energy Solutions",
    product: "Industrial automation / HVAC motor work",
    market: "industrial-drive",
    maturity: "vehicle-pilot",
    claimIds: ["industrial-induction-incumbent", "named-company-corrections"],
    correction: "Keep in the industrial efficiency market lane unless an EV traction product is verified.",
    needsVerification: true,
  },
] as const satisfies readonly CompanyExample[];
