import type { EvidenceSource } from "./schema.ts";

/**
 * Launch-gate sources distilled from `pmsm-evidence-work/evidence-audit`.
 * A due-diligence item may remain in the editorial ledger, but public wording
 * follows these sources and each claim's evidenceStatus/renderingPolicy.
 */
export const sources = [
  {
    id: "due-diligence-notes",
    title: "PMSM alternatives due diligence notes supplied for this visualisation",
    organisation: "Tannmay Kumarr Baid",
    sourceType: "due-diligence",
    date: "2026-08-09",
    note: "Primary editorial narrative and correction log. It is not a substitute for a public primary source.",
  },
  {
    id: "original-pmsm-report",
    title: "The Post-Rare-Earth Powertrain",
    organisation: "Akshashila / Pranay",
    sourceType: "secondary",
    date: "2026-08-09",
    note: "Backdrop only; disputed claims are corrected or suppressed by the evidence audit.",
  },
  {
    id: "doe-magnet-supply-chain",
    title: "Rare Earth Permanent Magnets: Supply Chain Deep Dive Assessment",
    organisation: "U.S. Department of Energy",
    sourceType: "primary",
    date: "2022-02-24",
    url: "https://www.energy.gov/sites/default/files/2022-02/Neodymium%20Magnets%20Supply%20Chain%20Report%20-%20Final.pdf",
    note: "Typical 1–2 kg of permanent magnet material per EV traction motor; composition and supply-chain context.",
  },
  {
    id: "clepa-magnet-disruption",
    title: "China's Export Restrictions on Rare Earths Disrupt Automotive Supply Chains",
    organisation: "CLEPA — European Association of Automotive Suppliers",
    sourceType: "primary",
    date: "2025-06-04",
    url: "https://www.clepa.eu/wp-content/uploads/2025/06/Statement_export-restrictions-by-China-rare-earths_PR_June-2025-CLEPA.pdf",
    note: "Supplier production disruptions, not proof that EV traction magnets alone stopped every affected line.",
  },
  {
    id: "acma-fy25-magnet-supply",
    title: "Indian Auto Component Industry Performance Review FY25",
    organisation: "ACMA — Automotive Component Manufacturers Association of India",
    sourceType: "primary",
    date: "2025-07-08",
    url: "https://www.acma.in/uploads/press-release/Press%20Release%20FY25.pdf",
    note: "Limited rare-earth magnet availability; does not establish licence denials or a universal price increase.",
  },
  {
    id: "ev-magnet-materials-review",
    title: "Emerging magnetic materials for electric vehicle drive motors",
    organisation: "OSTI",
    sourceType: "primary",
    date: "2024-07-02",
    url: "https://www.osti.gov/biblio/2391096",
  },
  {
    id: "china-april-2025-controls",
    title: "Announcement No. 18 of 2025 on export control of some medium and heavy rare-earth related items",
    organisation: "Ministry of Commerce of the People's Republic of China",
    sourceType: "primary",
    date: "2025-04-04",
    url: "https://english.mofcom.gov.cn/Policies/AnnouncementsOrders/art/2025/art_0dd87cbee7b045bf93fabe6ab2faceee.html",
  },
  {
    id: "ndfeb-coercivity-review",
    title: "Most frequently asked questions about the coercivity of Nd-Fe-B permanent magnets",
    organisation: "Peer-reviewed review article",
    sourceType: "primary",
    date: "2021-06-04",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8183520/",
  },
  {
    id: "ornl-gbd-coating",
    title: "Strategic coating of NdFeB magnets with Dy to improve the coercivity and energy product of permanent magnets",
    organisation: "Oak Ridge National Laboratory",
    sourceType: "primary",
    date: "2015-12-01",
    url: "https://www.ornl.gov/publication/strategic-coating-ndfeb-magnets-dy-improve-coercivity-and-energy-product-permanent",
  },
  {
    id: "proterial-hree-free",
    title: "Proterial Develops High-Performance Heavy-Rare-Earth-Free Neodymium Sintered Magnet for Electric Vehicle Driving Motors",
    organisation: "Proterial",
    sourceType: "company-claim",
    date: "2025-07-22",
    url: "https://www.proterial.com/e/press/2025/n0722b.html",
  },
  {
    id: "audi-q6-oil-cooling",
    title: "The Audi Q6 e-tron — Sporty performance: powerful drives",
    organisation: "Audi",
    sourceType: "primary",
    date: "2024-06-28",
    url: "https://www.audi.com/en/the-audi-q6-e-tron-electric-mobility-on-a-new-level-15929/sporty-performance-powerful-drives-15932",
  },
  {
    id: "doe-wound-field-report",
    title: "Brushless and Permanent Magnet Free Wound Field Synchronous Motors for EV Traction",
    organisation: "U.S. Department of Energy",
    sourceType: "primary",
    date: "2017-03-31",
    url: "https://www.osti.gov/servlets/purl/1349258",
  },
  {
    id: "bmw-gen6-asm",
    title: "BMW Group reveals 800V electric drive concept for the Neue Klasse",
    organisation: "BMW Group",
    sourceType: "primary",
    date: "2025-02-24",
    url: "https://www.press.bmwgroup.com/pressclub/p/ac/pressDetail.html?id=T0448216EN&left_menu_item=node__5251&outputChannelId=13&title=charge-faster-drive-further-bmw-group-reveals-revolutionary-electric-drive-concept-with-800v",
  },
  {
    id: "renault-eesm",
    title: "An electric motor with no rare earths: cutting-edge technology",
    organisation: "Renault Group",
    sourceType: "primary",
    date: "2025-10-16",
    url: "https://www.renaultgroup.com/en/magazine/energy-and-motorization/all-about-electric-motors-with-no-rare-earths/",
  },
  {
    id: "nissan-ariya",
    title: "Activities in the Development Stage",
    organisation: "Nissan",
    sourceType: "primary",
    date: "n.d.",
    url: "https://www.nissan-global.com/EN/SUSTAINABILITY/ENVIRONMENT/GREENPROGRAM/DEPENDENCY/PRODUCT/",
  },
  {
    id: "zf-i2sm",
    title: "I2SM — Inductively Excited Synchronous Machine",
    organisation: "ZF Friedrichshafen",
    sourceType: "company-claim",
    date: "n.d.",
    url: "https://www.zf.com/products/en/cars/products_77186.html",
  },
  {
    id: "valeo-ibee",
    title: "Valeo and MAHLE announce iBEE joint development",
    organisation: "Valeo / MAHLE",
    sourceType: "company-claim",
    date: "2024-10-14",
    url: "https://www.valeo.com/en/valeo-and-mahle-expand-their-product-range-of-magnet-free-electric-motors-to-upper-segment-applications-through-a-joint-development-of-ibee-inner-brushless-electrical-excitation/",
  },
  {
    id: "mahle-sct",
    title: "Compact endurance athlete — the new SCT E-motor by MAHLE",
    organisation: "MAHLE",
    sourceType: "company-claim",
    date: "2022-07-04",
    url: "https://www.mahle.com/global/media/global_news/2022/07-sct-e-motor/20220704_pressrelease_sct-e-motor.pdf",
  },
  {
    id: "volektra-patent",
    title: "Magnet-less and brush-less rotating transformer excited synchronous machine and method of its control",
    organisation: "Volektra Inc.",
    sourceType: "primary",
    date: "2024-05-30",
    url: "https://patents.google.com/patent/US20240178726A1/en",
  },
  {
    id: "vimag-technology",
    title: "VMSM Technology | Software-Defined Magnet-Free Motors",
    organisation: "Vimag",
    sourceType: "company-claim",
    date: "n.d.",
    url: "https://vi-mag.com/technology.html",
  },
  {
    id: "abb-ie5-synrm",
    title: "ABB IE5 SynRM Motors: Ultra-Efficient, Magnet-Free Power for Industrial Applications",
    organisation: "ABB",
    sourceType: "company-claim",
    date: "n.d.",
    url: "https://www.abb.com/global/en/areas/motion/motors-generators/low-voltage-motors/iec-low-voltage-motors/process-performance-motors/ie5-synchronous-reluctance-safe-area-motors",
  },
  {
    id: "doe-magnet-roadmap",
    title: "Barriers to the Application of High-Temperature Coolants in Hybrid Electric Vehicles",
    organisation: "U.S. Department of Energy",
    sourceType: "primary",
    date: "2006-09",
    url: "https://www.osti.gov/servlets/purl/947389-IEagpu/",
  },
  {
    id: "proterial-ferrite-test",
    title: "Output exceeding 100 kW applicable for traction motors verified on actual ferrite magnet motor",
    organisation: "Proterial",
    sourceType: "company-claim",
    date: "2023-07-24",
    url: "https://www.proterial.com/e/press/2023/pdf/20230724en.pdf",
  },
  {
    id: "tokyo-ferrite-cold-demag",
    title: "Basic Properties of Magnets — Low Temperature Demagnetization of a Ferrite Magnet",
    organisation: "Tokyo Ferrite",
    sourceType: "company-claim",
    date: "n.d.",
    url: "https://tokyoferrite-ho.co.jp/en/technical_data/behavior/behavior.html",
  },
  {
    id: "niron-variable-flux-patent",
    title: "Variable-flux-intensifying electric machines using iron nitride permanent magnets",
    organisation: "Niron Magnetics",
    sourceType: "primary",
    date: "2025-08-28",
    url: "https://patents.google.com/patent/WO2025178978A1/en",
  },
  {
    id: "fe16n2-thermal-paper",
    title: "Simultaneous tuning of the magnetic anisotropy and thermal stability of alpha-double-prime Fe16N2",
    organisation: "Peer-reviewed journal article",
    sourceType: "primary",
    date: "2021-04-09",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8035402/",
  },
  {
    id: "matter-niron-vfm",
    title: "MATTER and Niron Magnetics Unveil Next Generation Rare-Earth-Free Variable Flux Motor",
    organisation: "Matter / Niron Magnetics",
    sourceType: "company-claim",
    date: "2026-01-07",
    url: "https://nironmagnetics.com/news/matter-and-niron-magnetics-unveil-next-generation-rare-earth-free-variable-flux-motor",
  },
  {
    id: "aem-ssrd-datasheet",
    title: "SSRD Technology Datasheet",
    organisation: "Advanced Electric Machines",
    sourceType: "company-claim",
    date: "2025-11-01",
    url: "https://cdn.asp.events/CLIENT_CloserSt_D86EA381_5056_B739_5482D50A1A831DDD/sites/ivt-expo-europe-2025/media/libraries/exhibitor-brochures/843571-ssrd.pdf",
  },
  {
    id: "renault-futureready",
    title: "Renault Group futuREady press release",
    organisation: "Renault Group",
    sourceType: "primary",
    date: "2026-03-10",
    url: "https://media.renaultgroup.com/renault-group-launches-futuready-opening-a-new-strategic-era/?lang=eng",
  },
  {
    id: "naxatra-profile",
    title: "Introducing Naxatra Labs",
    organisation: "Rainmatter / Zerodha",
    sourceType: "company-claim",
    date: "2025-01-21",
    url: "https://zerodha.com/z-connect/rainmatter/introducing-naxatra-labs",
  },
  {
    id: "gati-products",
    title: "Gati Drives - SSPM Motor Manufacturing",
    organisation: "Gati Drives",
    sourceType: "company-claim",
    date: "n.d.",
    url: "https://www.gatidrives.com/",
  },
  {
    id: "ekmo-products",
    title: "EKMO — Rare-Earth-Free Motor Licensing | IE6 Ferrite Motors",
    organisation: "EKMO",
    sourceType: "company-claim",
    date: "n.d.",
    url: "https://www.ekmo.eu/",
  },
  {
    id: "conifer-products",
    title: "Conifer — Onshored Electric Powertrains",
    organisation: "Conifer",
    sourceType: "company-claim",
    date: "n.d.",
    url: "https://conifer.io/",
  },
  {
    id: "india-mhi-repm-policy",
    title: "Overcoming Shortage of Rare Earth Magnets for EV Production",
    organisation: "Ministry of Heavy Industries, Government of India",
    sourceType: "primary",
    date: "2025-12-12",
    url: "https://heavyindustries.gov.in/sites/default/files/2025-12/rsauq_1525.pdf",
  },
] as const satisfies readonly EvidenceSource[];
